ets-berkeley-edu/teena

pages/calcentral/canvas_site_creation_page.rb
pages/canvas_page.rb
settings.yml
spec/junction/canvas_lti_course_captures_spec.rb
spec/junction/canvas_lti_course_site_creation_spec.rb
util/utils.rb

Changes to site creation script:
- allow test runs using embedded tool (on a local machine) or standalone tool (either locally or on a server)
- add post-site-creation checks for roster photos and course captures tools

bCourses site creation test script enhancement

---

pages/canvas_page.rb
pages/suitec/asset_library_page.rb
pages/suitec/whiteboards_page.rb
spec/suitec/asset_library_manage_assets_spec.rb
spec/suitec/canvas_assignment_submissions_spec.rb
spec/suitec/canvas_assignment_sync_spec.rb
spec/suitec/canvas_discussions_spec.rb
spec/suitec/engagement_index_spec.rb
spec/suitec/whiteboard_collaboration_spec.rb

Changes:
- Check that the _suitec file folder is hidden
- Handle course sites where Canvas sync is disabled
- Verify that users removed from course sites lose access to tools as expected
In a couple of scripts, variable declarations had to be moved out of 'before' hooks to make them accessible to other 'describe' blocks.  This accounts for most of the changed lines.

SuiteC test updates for v1.8

---

pages/cal_net_page.rb
pages/canvas_page.rb
pages/junction/canvas_create_course_site_page.rb
pages/suitec/asset_library_page.rb
pages/suitec/whiteboards_page.rb
spec/junction/canvas_lti_rosters_spec.rb
spec/suitec/asset_library_content_spec.rb
spec/suitec/asset_library_uploads_spec.rb
spec/suitec/asset_library_urls_spec.rb
spec/suitec/canvas_assignment_sync_spec.rb
spec/suitec/engagement_index_points_config_spec.rb
spec/suitec/whiteboard_collaboration_spec.rb
spec/suitec/whiteboard_management_spec.rb

- The looping "asset library content" script is mainly intended to verify handling of various asset types (e.g., preview service), but it also checks activity points updates for each asset.  The latter means it performs the same test over and over again for every file and every URL.  The activity point test are now moved to scripts that perform the checks once only.
- Misc other tweaks to UI handling, including continuing reduction in use of JS for click()-ing.

Reduce test execution time, fix minor problems handling UI

---

pages/suitec/impact_studio_page.rb
spec/suitec/impact_studio_assets_spec.rb

Expands the hideous asset impact score tests to include event counts on the user activity event drops SVG.  The script is so far unable to interact with the "metaballs" themselves, so it relies on the event count shown on the axis label to verify the SVG data.

Rudimentary tests for activity timeline drops

---

pages/page.rb
spec/junction/canvas_lti_mailing_lists_spec.rb

Two changes:
- If clicking via JS fails, then try a WebDriver click
- "Pending" users won't be added to a mailing list, so make sure test users accept the course invite

Minor Junction test fixes

---

models/suitec/activity.rb
pages/suitec/asset_library_page.rb
pages/suitec/impact_studio_page.rb
pages/suitec/suite_c_pages.rb
spec/suitec/impact_studio_assets_spec.rb
spec/suitec/impact_studio_visualizations_spec.rb

Changes:
- Creates tests for the event drops on the asset detail
- Splits the impact visualizations tests into their own script, separate from the asset swim lane tests
- Shares the visualization interactions with both the Impact Studio page and the Asset Library page

Asset activity viz tests

---

pages/canvas/canvas_page.rb
pages/page.rb
pages/suitec/asset_library_page.rb
pages/suitec/suite_c_pages.rb
spec/junction/canvas_lti_mailing_lists_spec.rb
spec/suitec/canvas_assignment_submissions_spec.rb
spec/suitec/canvas_assignment_sync_spec.rb
spec/suitec/canvas_discussions_spec.rb
spec/suitec/engagement_index_spec.rb
spec/suitec/whiteboard_collaboration_spec.rb

Main changes:
- Since there was no way to know when the Canvas poller would sync a test course, many tests waited a generous and fixed amount of time before assuming the syncing had occurred.  Instead, the tests now perform an unrelated activity that should be picked up by the poller and be detectable in the SuiteC UI once updated.  That way, the test knows the poller has synced the course.
- Previously, users required by a test were added to a pre-existing course site even if they were already on the site.  Now, the tests don't bother re-adding the same users.
- The new Canvas UI requires some locator updates.
- The Canvas class has its methods rearranged into a more logical order.

Speed up test execution

---

pages/suitec/whiteboards_page.rb
spec/suitec/whiteboard_collaboration_spec.rb

Changes the sequence of some whiteboard tests, since some kind of Chromedriver bug obliterates the sidebar header on an open whiteboard.  The new sequence works around the problem.

Fix whiteboard tests

---

pages/canvas/canvas_activities_page.rb
pages/canvas/canvas_page.rb
pages/page.rb
pages/suitec/impact_studio_page.rb
pages/suitec/suite_c_pages.rb
spec/suitec/asset_library_content_spec.rb
spec/suitec/asset_library_manage_assets_spec.rb
spec/suitec/asset_library_pins_spec.rb
spec/suitec/canvas_assignment_sync_spec.rb
spec/suitec/engagement_index_spec.rb
spec/suitec/impact_studio_assets_spec.rb
spec/suitec/impact_studio_visualizations_spec.rb
spec/suitec/whiteboard_management_spec.rb

- Make sure SuiteC test scripts give their assets unique titles so that the asset ID can always be obtained
- Add a test for assignments with non-sync-able submission types

More v2.3 test fixes

---

pages/cal_net_page.rb
settings.yml
util/utils.rb

Avoid having to do 2-step auth for every test by using custom Chrome and Firefox profiles where authenticated session is maintained.

Use custom browser profiles to avoid relentless 2-step auth

---

pages/cal_net_page.rb
pages/junction/splash_page.rb
spec/junction/canvas_lti_course_site_creation_spec.rb
spec/junction/canvas_lti_e_grades_export_spec.rb
spec/junction/canvas_lti_official_sections_spec.rb
spec/junction/canvas_lti_rosters_spec.rb

With 2-step auth, switching between basic auth and LTI auth was causing more session conflicts that killed test runs.  This change alters the sequence of steps in the create a site and official sections scripts.  Previously, the order was "course 1 - collect SIS data and run tests; course 2 - collect SIS data and run tests".  Now the order is "courses 1 and 2 - collect SIS data; courses 1 and 2 - run tests".

Rework Junction scripts to avoid auth conflicts

---

spec/junction/canvas_lti_official_sections_spec.rb

This change only verifies Lead TAs can see the "edit" button, but the external test data file that determines which test users are used for the full script now includes both teachers and Lead TAs.

Lead TA can manage official sections

---

pages/oec/blue_page.rb

Don't click file input, just send_keys.

Fix file upload in OEC script

---

pages/canvas/canvas_activities_page.rb
pages/suitec/asset_library_page.rb
scripts/suitec_activity_network_script.rb
util/utils.rb

Script loads a CSV and performs the actions indicated in each of the CSV rows. A sample CSV will be added separately. The script takes a screenshot of the Activity Network after each action.

Simple script to perform configurable collaboration activities

---

pages/canvas/canvas_page.rb
spec/junction/canvas_lti_mailing_lists_spec.rb

Canvas has changed its search-for-course UX, which also breaks the mailing list test.

Fix mailing list test

---

spec/boac/boac_dashboard_teams_spec.rb

A long-running script often hits interruptions caused by deploys, leaving it with an unfamiliar UI.  Instead of looking for the Home button for each user, just hit the homepage URL.

Avoid total script failures caused by deploys

---

pages/boac/api_user_analytics_page.rb
pages/boac/student_page.rb
spec/boac/boac_team_member_data_spec.rb

Script now follows three tracks per user, inspecting and exporting:
- SIS profile data
- SIS course section data
- Canvas course site data, matched and unmatched
A lot of indentation changes.

Handle secondary sections in BOAC tests

---

pages/canvas/canvas_page.rb
pages/page.rb
pages/suitec/whiteboards_page.rb
settings.yml
spec/suitec/asset_library_comments_spec.rb
spec/suitec/asset_library_likes_spec.rb
spec/suitec/asset_library_pins_spec.rb
spec/suitec/engagement_index_spec.rb
spec/suitec/impact_studio_assets_spec.rb
spec/suitec/impact_studio_search_spec.rb
spec/suitec/whiteboard_assets_spec.rb
spec/suitec/whiteboard_collaboration_spec.rb
spec/suitec/whiteboard_management_spec.rb
util/suite_c_utils.rb

Test scripts now compare the events tracked to the events written to the events table.  Since minor diffs seem to be unavoidable, the scripts do not expect exact matches.  Instead, they check whether the numbers are within a configurable range of one another.  They also create a CSV of events tracked and a CSV of events in the table for manual debugging.

Verify SuiteC events

---

pages/canvas/canvas_activities_page.rb
settings.yml
spec/boac/boac_analytics_spec.rb
spec/boac/boac_team_member_data_spec.rb
util/boac_utils.rb

The comparison of analytics from Canvas API with analytics from Data Loch is moved to its own test script.  The new test script also compares current scores in the Data Loch with those in the gradebook CSV export.

Tests for current scores analytics

---

pages/boac/api_user_analytics_page.rb
pages/canvas/canvas_announce_discuss_page.rb
pages/canvas/canvas_assignments_page.rb
pages/canvas/canvas_page.rb
spec/boac/boac_team_analytics_data_spec.rb

Tests now compare counts of both assignments submitted and those submitted on-time.  Comparison is the student view of the assignment UI in Canvas versus the BOAC data derived from the Loch.

Fixes for assignment submission tests

---

pages/boac/home_page.rb
pages/boac/student_page.rb
spec/boac/boac_alerts_spec.rb
util/boac_utils.rb

Dismissing, hiding, revealing alerts on the student page.  Still to come: alert visibility on the homepage.

Simple alerts test

---

spec/suitec/asset_library_comments_spec.rb
spec/suitec/asset_library_likes_spec.rb
spec/suitec/asset_library_pins_spec.rb
spec/suitec/whiteboard_assets_spec.rb
spec/suitec/whiteboard_management_spec.rb

Recycled course sites already have a pile of events from previous test runs.

Do not test events on recycled course sites

---

pages/boac/student_page.rb
spec/boac/boac_team_assignments_data_spec.rb
spec/boac/boac_team_last_activity_spec.rb
util/utils.rb

Mostly indentation change... if a BOAC script requires admin Canvas access but is set to run headlessly, the script will now abort.

Flag tests that cannot run headless

---

models/oec/oec_departments.rb
pages/oec/blue_page.rb
util/oec_utils.rb

OEC has evaluation forms with/without types (e.g., F and G) and with/without course number restrictions (e.g., 290).  This updates to test script to handle more variations.

Test updates to handle complex OEC dept forms

---

pages/suitec/engagement_index_page.rb

SuiteC's CSV download link kills the latest version of Chrome when run by ChromeDriver.

Fix SuiteC CSV tests

---

settings.yml
util/utils.rb

With the latest Chrome, Chromedriver blows up when maximizing the window, so skip maximizing for now.

Removing window sizing

---

models/boac/boac_test_config.rb
pages/boac/boac_pages.rb
pages/boac/cohort_pages.rb
pages/boac/home_page.rb
pages/boac/search_results_page.rb
spec/boac/boac_filtered_cohort_spec.rb
spec/boac/boac_team_sis_data_spec.rb
spec/boac/boac_user_role_admin_spec.rb
spec/boac/boac_user_role_asc_spec.rb
spec/boac/boac_user_role_coe_spec.rb
spec/boac/boac_user_search_spec.rb

Removes the ASC-specific logic from the test script for BOAC SIS data (causing lots of changes to indentation). Also fixes a few small test bugs.

SIS tests can finally run for non-athletes

---

models/boac/boac_test_config.rb
models/boac/cohort.rb
models/boac/cohort_filter.rb
models/boac/filtered_cohort.rb
pages/boac/boac_pages.rb
pages/boac/class_list_view_page.rb
pages/boac/class_matrix_view_page.rb
pages/boac/filtered_cohort_page.rb
pages/boac/home_page.rb
pages/boac/search_results_page.rb
pages/boac/student_page.rb
pages/boac/user_list_pages.rb
pages/junction/splash_page.rb
settings.yml
spec/boac/boac_class_pages_spec.rb
spec/boac/boac_curated_group_spec.rb
spec/boac/boac_filtered_cohort_spec.rb
spec/boac/boac_navigation_spec.rb
spec/boac/boac_team_sis_data_spec.rb
spec/boac/boac_user_role_admin_spec.rb
spec/boac/boac_user_role_coe_spec.rb
util/boac_utils.rb
util/nessie_utils.rb
util/utils.rb

Includes
- Handles UI and logic changes for curated groups
- Adds tests for groups on homepage
- Adds tests for new CoE cohort filters
- Fixes tests broken by accessibility fixes
Bonus
- Adds a workaround in Junction tests for the auth-test bug
- Enlarges browser window size to avoid not-clickable errors in headless mode

Test updates and fixes for BOAC v2.10 changes

---

spec/junction/canvas_lti_course_add_user_spec.rb
spec/junction/canvas_lti_rosters_spec.rb
spec/junction/junction_background_tasks_spec.rb

Always start with a fresh course site, since recycled sites can contain data that will cause false failures.  Also, use the same admin account for all tests.

Avoid test failures caused by previous test runs

---

pages/boac/boac_cohort_pages.rb
pages/boac/boac_filtered_cohort_page.rb
pages/boac/boac_home_page.rb
pages/boac/boac_pages.rb
pages/boac/boac_user_list_pages.rb
spec/boac/boac_filtered_cohort_spec.rb

https://jira.ets.berkeley.edu/jira/browse/BOAC-1649
Teena now finds menu options in new `/cohort` design.

BOAC-1649, correct /cohort URL; use new ids on BOAC

---

models/boac/boac_test_config.rb
models/boac/cohort_filter.rb
pages/boac/boac_filtered_cohort_page.rb
settings.yml
spec/boac/boac_curated_group_spec.rb
spec/boac/boac_filtered_cohort_spec.rb
spec/boac/boac_user_role_coe_spec.rb
spec/boac/boac_user_role_physics_spec.rb
util/boac_utils.rb
util/nessie_utils.rb

- Incorporates Physics student data into tests
- Adds a test for the Physics advisor view
- Makes another attempt to untangle the way department customizations are handled

Handle physics cohorts

---

pages/page.rb

Clicking the translucent footer now clicks the elements beneath, so hide the footer with JS instead.

Handle change to Canvas footer

---

spec/boac/boac_legacy_notes_spec.rb
util/utils.rb

Legacy note tests will search with previously disallowed characters, and Teena won't stick the date on test results twice.

Allow all search characters, fix test results file name

---

pages/junction/api_academics_roster_page.rb
spec/junction/canvas_lti_course_site_creation_spec.rb
spec/junction/canvas_lti_e_grades_api_spec.rb

- If course site student enrollment doesn't match expectations, log the mismatching UIDs
- Use a new Chrome profile for E-Grades tests, since the E-Grades Export button won't appear without a hard refresh if Canvas/Junction environments have been switched around

Small tweaks to Junction tests

---

pages/boac/boac_admin_page.rb
pages/page.rb
spec/boac/boac_user_role_admin_spec.rb

https://jira.ets.berkeley.edu/jira/browse/BOAC-2180
This can be merged after https://github.com/ets-berkeley-edu/boac/pull/1552 is merged.
The textbox was tricky to 'clear'.

BOAC-2180, service-announcement textarea converted to ckEditor textbox

---

settings.yml
util/utils.rb

https://stackoverflow.com/questions/56111529/cannot-call-non-w3c-standard-command-while-in-w3c-mode-seleniumwebdrivererr

QA workaround for Chrome 75 issue

---

pages/boac/boac_pages_create_note_modal.rb
pages/boac/boac_student_page_advising_note.rb
spec/boac/boac_note_batch_spec.rb

https://jira.ets.berkeley.edu/jira/browse/BOAC-2289
And no more `send_keys` in student (auto-complete) dropdown.

BOAC-2289, verify note on student profile if student is in curated group of batch note

---

pages/boac/boac_pages_create_note_modal.rb
pages/boac/boac_student_page_advising_note.rb
settings.yml
spec/boac/boac_note_batch_spec.rb
util/boac_utils.rb

https://jira.ets.berkeley.edu/jira/browse/BOAC-2287
https://jira.ets.berkeley.edu/jira/browse/BOAC-2286
Includes:
* new configs to control scale of batch-note creation:  `notes_batch_curated_group_count`, `notes_batch_students_count`, `notes_batch_students_per_group_count`
* verification of `unique_students_in_batch`

BOAC-2287 / BOAC-2275, verify student count when batch note create

---

models/boac/boac_test_config.rb
models/boac/cohort_filter.rb
pages/boac/boac_cohort_pages.rb
pages/boac/boac_filtered_cohort_page_filters.rb
pages/boac/boac_filtered_cohort_page_results.rb
spec/boac/boac_filtered_cohort_spec.rb
test_data/test-data-boac.json
util/nessie_utils.rb

- Replaces l_and_s students with undergrads
- Converts the cohort test script to an admin-only script to exercise all filters
- Updates the test data file, and cuts the cohort test script run time in half
- Standardizes naming conventions for filters

Expand student population and fix filter tests

---

settings.yml
spec/junction/canvas_lti_course_add_user_spec.rb

Canvas isn't reliably finding site members unless the full roster is loaded, so this change loads the whole roster before searching for users added via the add-user tool.

Fix Junction add-user tests

---

pages/boac/boac_home_page.rb
pages/boac/boac_user_list_pages.rb

https://jira.ets.berkeley.edu/jira/browse/BOAC-2828
Corresponding BOA PR is https://github.com/ets-berkeley-edu/boac/pull/2000

BOAC-2828, ids have changed on elements 'home-cohort-...' and 'home-curated-...'

---

pages/canvas/canvas_page.rb

Canvas changed its site publishing workflow in Beta, and now it's changed it back.

Revert change to site publishing workflow

---

pages/boac/boac_home_page.rb

https://jira.ets.berkeley.edu/jira/browse/BOAC-3044
Minor Teena adjustments per https://github.com/ets-berkeley-edu/boac/pull/2172

BOAC-3044, Teena: remove 'splash-' prefix from id and class refs (login)

---

spec/boac/boac_search_spec.rb

Legacy notes can have null subject. A few lines after this change you'll see `generate_note_search_query()` which contains a similar null check.

Teena: note.subject null check

---

load_tests/boa_locust.py

Spawning deleted users will get you lotsa API call failures.

Small load test fix

---

pages/canvas/canvas_page.rb

Test blew up since there was a higher student count on the enrollment dropdown than there were student rows on the site.

Handle enrollment count mismatch better in site creation tests

---

pages/boac/boac_filtered_cohort_page_results.rb

I had adapted tests to BOA behavior before the relevant BOA PR had been merged, so I'm undoing them.  Also, I've left the units and GPA(cumul) sort-descending tests in a failing state, since I think BOA's current behavior is wrong.

Undo previous sorting test changes

---

models/boac/cohort.rb
pages/boac/boac_cohort_pages.rb
pages/boac/boac_filtered_admits_page.rb
spec/boac/boac_filtered_admits_spec.rb

The tests should only be executed against the full CE3 "cohort" in BOAC-3426, but until the full cohort is present in the UI they'll run against each test cohort (which produces lots of benign test failures).

Tests for CE3 CSV export

---

spec/suitec/canvas_assignment_submissions_spec.rb

Check the CSV all at once, rather than each submission at a time.

Speed up SuiteC tests

---

spec/boac/boac_filtered_cohort_spec.rb

Instead of executing cohort sorting tests using multiple cohorts, just test the cohort with the most members.  Saves a lot of time.

Stop sorting so many cohorts

---

models/boac/boac_test_config.rb
models/boac/note_source.rb
pages/element.rb
settings.yml
spec/boac/boac_note_content_spec.rb
util/boac_utils.rb
util/nessie_utils.rb

Makes sure all note sources plus attachments are tested with the minimum test users.  Much of the diff is an indent change.

More efficient tests for existing notes

---

load_tests/boa_locust.py

The waitlist polling tests were logging in advisors who then had no access to most of the cohort IDs in the test data.  This changes the test to use admins only and hit a hard-coded QCADV waiting list.

Fix BOA load test

---

pages/boac/boac_home_page.rb

The dismissal of `fixed-warning-on-all-pages` is done elsewhere: https://github.com/ets-berkeley-edu/teena/blob/master/pages/page.rb#L48

NOJIRA, 'fixed_warning' in footer may be absent; wait for copyright_year_login_element instead

---

pages/junction/canvas_create_course_site_page.rb
pages/junction/junction_pages.rb
spec/junction/canvas_job_refresh_canvas_recent_spec.rb
spec/junction/canvas_lti_course_add_user_spec.rb
spec/junction/canvas_lti_course_captures_spec.rb
spec/junction/canvas_lti_course_site_creation_spec.rb
spec/junction/canvas_lti_e_grades_api_spec.rb
spec/junction/canvas_lti_e_grades_export_spec.rb
spec/junction/canvas_lti_mailing_lists_spec.rb
spec/junction/canvas_lti_official_sections_spec.rb
spec/junction/canvas_lti_project_site_creation_spec.rb
spec/junction/canvas_lti_rosters_spec.rb
spec/junction/canvas_lti_user_provisioning_spec.rb
spec/junction/junction_background_tasks_spec.rb
util/junction_utils.rb

Except E-Grades and mailing list tests, which are too enmeshed in Canvas.  A significant part of the diff is indent change.

Allow Junction LTI tests to be run outside Canvas

---

models/oec/oec_departments.rb
spec/junction/canvas_lti_course_add_user_spec.rb
spec/junction/canvas_lti_e_grades_export_spec.rb
spec/junction/canvas_lti_mailing_lists_spec.rb
spec/junction/canvas_lti_official_sections_spec.rb
spec/junction/canvas_lti_rosters_spec.rb

Canvas changed the way non-authorized users were blocked from Junction tools... and now they've changed it back.

Revert LTI perms changes

---

spec/junction/canvas_lti_course_add_user_spec.rb
spec/junction/canvas_lti_e_grades_export_spec.rb
spec/junction/canvas_lti_mailing_lists_spec.rb
spec/junction/canvas_lti_official_sections_spec.rb
spec/junction/canvas_lti_rosters_spec.rb

Canvas is blocking tool access again, so update tests to handle either means of verifying that non-auth users are blocked from tools.

Fix tests for tool access denial

---

pages/boac/boac_api_student_page.rb
pages/canvas/canvas_page.rb
pages/junction/api_academics_roster_page.rb
spec/boac/boac_sis_student_data_spec.rb
spec/junction/canvas_lti_rosters_spec.rb
util/boac_utils.rb

Changes the sequence of tests to reduce page loads, cutting execution time by a third.  Plus a couple Canvas test fixes.

Cut execution time for BOA student SIS data tests

---

models/squiggy/squiggy_course.rb
models/test_config.rb
pages/canvas/canvas_page.rb
settings.yml
util/squiggy_utils.rb

Instead of configuring LTI tools for each test, copy a test course site maintained in Canvas Prod with tools already configured.  Appears to reduce execution time of the suite by ~30 minutes overall.

Reduce Squiggy test execution time

---

pages/canvas/canvas_api_page.rb
pages/ripley/ripley_create_course_site_page.rb
spec/ripley/course_site_creation_spec.rb
spec/ripley/customizations_and_add_user_spec.rb
spec/ripley/e_grades_export_spec.rb
spec/ripley/e_grades_validation_spec.rb
spec/ripley/mailing_lists_spec.rb
spec/ripley/official_sections_spec.rb
spec/ripley/refresh_canvas_recent_manual_spec.rb
spec/ripley/refresh_canvas_recent_spec.rb
spec/ripley/roster_photos_spec.rb
spec/ripley/user_provisioning_spec.rb
spec/ripley/welcome_email_spec.rb
util/ripley_utils.rb

Almost all indent changes.  Ripley standalone is meaningless for testing LTI tools, and it adds too much complexity to already complex scripts.

Ditch standalone mode in Ripley tests
