pages/cal_net_page.rb, pages/canvas_page.rb, pages/suitec/asset_library_page.rb, pages/suitec/whiteboards_page.rb, spec/suitec/asset_library_categories_and_search_spec.rb, spec/suitec/asset_library_comments_spec.rb, spec/suitec/asset_library_likes_spec.rb, spec/suitec/asset_library_manage_assets_spec.rb, spec/suitec/canvas_assignment_sync_spec.rb, spec/suitec/whiteboard_management_spec.rb
New tests:
- Whiteboard deleting
- Whiteboard assets on asset detail views
- Asset migration
Plus some clean-up
=> SuiteC: new tests for v1.7

pages/calcentral/canvas_create_course_site_page.rb, pages/calcentral/my_academics_course_captures_card.rb, pages/canvas_page.rb, pages/suitec/asset_library_page.rb, pages/suitec/whiteboards_page.rb, spec/junction/canvas_lti_course_site_creation_spec.rb, spec/junction/my_academics_course_captures_spec.rb, spec/junction/my_dashboard_canvas_integration_spec.rb, spec/suitec/asset_library_categories_and_search_spec.rb, spec/suitec/asset_library_content_spec.rb, spec/suitec/asset_library_uploads_spec.rb, spec/suitec/asset_library_urls_spec.rb, spec/suitec/whiteboard_assets_spec.rb
Includes the following:
- Junction: 
Course capture test no longer looks for RSS and iTunes
bCourses site provisioning test reports how many users of different roles end up added to each site
- SuiteC:
Better handling of DOM updates and better logging of test results
=> Final script updates for v1.7 and v86

scripts/oec_data_source_script.rb
Script to update data sources in Blue:
* Waits for user to manually log in to Blue (either Prod or QA)
* Updates hard-coded "campus" data sources (by connecting to a known file path) and/or  variable "extension" data sources (by uploading all csv files in a specific local dir)
* Writes results to a local log file
=> CLC-6578 - OEC data source update script

logging.rb, pages/page.rb, scripts/lrs_canvas_events_assignments_script.rb, scripts/lrs_canvas_events_discussions_script.rb, scripts/lrs_canvas_events_groups_script.rb, util/utils.rb
- Logging now goes to a file instead of STDOUT
- LRS scripts now have the option to recycle existing Canvas course sites
- Script execution speed gets a small tweak
=> Logging and LRS script enhancements

pages/junction/canvas_mailing_lists_page.rb, pages/junction/junction_pages.rb, pages/page.rb, pages/suitec/asset_library_page.rb, pages/suitec/impact_studio_page.rb, pages/suitec/suite_c_pages.rb, scripts/oec_data_source_script.rb, spec/junction/canvas_lti_mailing_lists_spec.rb, spec/suitec/asset_library_categories_and_search_spec.rb, spec/suitec/impact_studio_assets_spec.rb, util/utils.rb
- Asset search test now cover new sort/filter options plus awareness of Impact Studio
- OEC script has some page elements updated
- Mailing list tests no longer expect CalMail option
=> Asset search, Mailgun mailing lists, and OEC script

models/suitec/activity.rb, pages/suitec/impact_studio_page.rb, scripts/suitec_impact_studio_trending_script.rb, settings.yml, spec/suitec/impact_studio_assets_spec.rb, util/utils.rb
Plus a script to generate impactful assets, which will be used to verify that trending asset calculations are occurring correctly.
=> Test coverage for individual event drops meatballs

pages/suitec/asset_library_page.rb, pages/suitec/impact_studio_page.rb, pages/suitec/suite_c_pages.rb, spec/suitec/asset_library_pins_spec.rb
Does not yet include Impact Studio pinned lanes.
=> Test for pinning and unpinning in asset library

pages/canvas/canvas_page.rb, pages/suitec/asset_library_page.rb, pages/suitec/impact_studio_page.rb, pages/suitec/suite_c_pages.rb, pages/suitec/whiteboards_page.rb, settings.yml, spec/suitec/asset_library_categories_and_search_spec.rb, spec/suitec/asset_library_content_spec.rb, spec/suitec/canvas_assignment_submissions_spec.rb, spec/suitec/impact_studio_assets_spec.rb, spec/suitec/impact_studio_visualizations_spec.rb, spec/suitec/whiteboard_assets_spec.rb, spec/suitec/whiteboard_collaboration_spec.rb
- Tests for pins in the Impact Studio and the "show more" links for all swim lanes
- Numerous test fixes associated with the AWS move
=> Tests for pins in Impact Studio plus misc test fixes

models/suitec/activity.rb, pages/canvas/canvas_page.rb, pages/suitec/asset_library_page.rb, pages/suitec/engagement_index_page.rb, pages/suitec/impact_studio_page.rb, pages/suitec/suite_c_pages.rb, spec/suitec/asset_library_categories_and_search_spec.rb, spec/suitec/asset_library_pins_spec.rb, spec/suitec/impact_studio_assets_spec.rb, spec/suitec/impact_studio_profile_summary_spec.rb, spec/suitec/impact_studio_visualizations_spec.rb, util/utils.rb
Big slew of test updates based on v2.1 changes.
=> v2.1 test updates

spec/suitec/impact_studio_assets_spec.rb, spec/suitec/impact_studio_visualizations_spec.rb
Impact Studio scripts cannot recycle existing course sites.
=> Remove course ID varible

Rakefile, pages/canvas/canvas_activities_page.rb, pages/canvas/canvas_page.rb, pages/suitec/engagement_index_page.rb, pages/suitec/impact_studio_page.rb, pages/suitec/suite_c_pages.rb, pages/suitec/whiteboards_page.rb, spec/suitec/asset_library_categories_and_search_spec.rb, spec/suitec/engagement_index_spec.rb, spec/suitec/impact_studio_profile_summary_spec.rb, spec/suitec/impact_studio_search_spec.rb, spec/suitec/whiteboard_collaboration_spec.rb
- Tests for collaboration UI in EI and IS
- Handle Canvas publish-course change
- Misc test fixes
=> Looking for collaborators

pages/canvas/canvas_page.rb, spec/junction/canvas_lti_mailing_lists_spec.rb, spec/junction/canvas_lti_rosters_spec.rb, test_data/test-data-bcourses.json
Tiny fixes, plus moved a "create course site" method to a more sensible location.
=> Itsy bitsy fixes

pages/cal_net_page.rb, pages/canvas/canvas_activities_page.rb, pages/canvas/canvas_page.rb, pages/page.rb, pages/suitec/asset_library_page.rb, pages/suitec/suite_c_pages.rb, pages/suitec/whiteboards_page.rb, spec/junction/canvas_lti_course_add_user_spec.rb, spec/suitec/asset_library_categories_and_search_spec.rb, spec/suitec/asset_library_content_spec.rb, spec/suitec/asset_library_uploads_spec.rb, spec/suitec/canvas_assignment_submissions_spec.rb, spec/suitec/canvas_assignment_sync_spec.rb, spec/suitec/whiteboard_assets_spec.rb, util/db_utils.rb
Changes:
- Tweaks to ensure that Firefox can scroll to elements and click them successfully
- Better validation that upload-asset-to-whiteboard really creates new assets
- Validation that there ain't no files being added to Canvas and that files downloaded from S3 match the file that was uploaded
- misc other
=> QA test fixes for SuiteC v2.3

pages/junction/api_academics_course_provision_page.rb, pages/junction/canvas_create_course_site_page.rb, spec/junction/canvas_lti_course_site_creation_spec.rb
Adds tests for Lead TA role and for form validation.
=> Create course site test fixes

models/event_type.rb, pages/canvas/canvas_activities_page.rb, pages/canvas/canvas_page.rb, spec/lrs/lrs_events_assignments_spec.rb, util/junction_utils.rb, util/lrs_utils.rb, util/suite_c_utils.rb, util/utils.rb
Plus some unrelated util fixes.
=> Test for assignment events

models/course.rb, models/section.rb, models/user.rb, pages/canvas/canvas_page.rb, pages/junction/canvas_course_add_user_page.rb, settings.yml, spec/lrs/lrs_events_assignments_spec.rb, spec/lrs/lrs_events_discussions_spec.rb, spec/lrs/lrs_events_enrollments_spec.rb, spec/lrs/lrs_events_groups_spec.rb, test_data/test-data-lrs.json, util/junction_utils.rb, util/lrs_utils.rb, util/suite_c_utils.rb, util/utils.rb
Tests cover manual enrollment events in Canvas as well as SIS imports.
=> Canvas enrollment events in LRS

models/suitec/asset.rb, models/suitec/comment.rb, pages/canvas/canvas_page.rb, pages/suitec/asset_library_page.rb, spec/junction/canvas_lti_rosters_spec.rb, spec/suitec/asset_library_categories_and_search_spec.rb, spec/suitec/asset_library_comments_spec.rb, spec/suitec/asset_library_manage_assets_spec.rb, spec/suitec/engagement_index_spec.rb, spec/suitec/impact_studio_assets_spec.rb, spec/suitec/impact_studio_visualizations_spec.rb, spec/suitec/whiteboard_assets_spec.rb, util/spec_helper.rb
Also a small change to waiting for SIS enrollment imports to finish.
=> Make comments objects not strings

pages/canvas/canvas_page.rb, pages/suitec/impact_studio_page.rb, spec/suitec/impact_studio_activity_network_spec.rb, util/suite_c_utils.rb
Plus a new Canvas Beta "add course" UI.
=> Activity Network test fixes

pages/canvas/canvas_page.rb, settings.yml, spec/junction/canvas_lti_course_add_user_spec.rb, spec/junction/canvas_lti_course_site_creation_spec.rb, spec/junction/canvas_lti_e_grades_export_spec.rb, util/utils.rb
Better logging of test results, supporting headless Firefox, and various other fixes.
=> Misc test updates

models/boac/cohort.rb, pages/boac/boac_pages.rb, pages/boac/cohort_page.rb, pages/boac/home_page.rb, spec/boac/boac_custom_cohort_spec.rb, util/boac_utils.rb
Tests for additional search filters are still pending.
=> Tests for create, manage, and delete cohorts

pages/canvas/canvas_page.rb, pages/junction/canvas_course_add_user_page.rb, pages/junction/canvas_course_captures_page.rb, pages/junction/canvas_course_manage_sections_page.rb, pages/junction/canvas_e_grades_export_page.rb, pages/junction/canvas_mailing_list_page.rb, pages/junction/canvas_mailing_lists_page.rb, pages/junction/canvas_rosters_page.rb, pages/junction/canvas_site_creation_page.rb, pages/junction/junction_pages.rb, pages/page.rb, pages/suitec/asset_library_page.rb, pages/suitec/impact_studio_page.rb, pages/suitec/suite_c_pages.rb, settings.yml, util/suite_c_utils.rb
- Junction tests make sure right Junction environment is configured in Canvas
- SuiteC tests interact with tooltips better
- Obsolete SuiteC test code removed
=> Junction and SuiteC test fixes

pages/boac/api_user_analytics_page.rb, pages/boac/cohort_page.rb, pages/boac/student_page.rb, spec/boac/boac_team_member_data_spec.rb, util/boac_utils.rb
- updates tests to handle latest UI changes
- cuts over to normalized boac-shared tables
=> More BOAC SIS data test fixes

pages/boac/api_user_analytics_page.rb, pages/boac/cohort_page.rb, pages/boac/student_page.rb, pages/page.rb, spec/boac/boac_team_member_data_spec.rb
Much of the diff in the test script itself is furniture rearranging to reduce code duplication.
=> Tests adapted to current analytics UI

models/boac/cohort_search_criteria.rb, models/user.rb, pages/boac/api_user_analytics_page.rb, pages/boac/boac_pages.rb, pages/boac/cohort_page.rb, pages/boac/student_page.rb, spec/boac/boac_custom_cohort_spec.rb, spec/boac/boac_team_member_data_spec.rb, util/boac_utils.rb
The actual search combinations will be added to the test_data dir in another PR.
=> Search test includes all filters and sorting

pages/boac/cohort_page.rb, pages/canvas/canvas_activities_page.rb, spec/suitec/whiteboard_collaboration_spec.rb, util/boac_utils.rb, util/junction_utils.rb, util/lrs_utils.rb, util/oec_utils.rb, util/suite_c_utils.rb, util/utils.rb
- Fixes broken interaction with Canvas discussion reply UI
- Adds support for using different browser profiles (to fix broken WebSocket tests)
- Fixes a random BOAC interaction too
=> Fix SuiteC tests

models/boac/cohort.rb, models/boac/squad.rb, models/boac/team.rb, pages/boac/api_user_analytics_page.rb, pages/boac/cohort_list_view_page.rb, pages/boac/cohort_page.rb, pages/boac/home_page.rb, pages/boac/student_page.rb, settings.yml, spec/boac/boac_custom_cohort_spec.rb, spec/boac/boac_navigation_spec.rb, spec/boac/boac_team_member_data_spec.rb, util/boac_utils.rb
- Handle new functional and UI changes (cohort filter changes, active status, etc)
- Fix bugs in tests
- Make Cohort / Team / Squad model structure more sensible
=> Numerous BOAC test fixes

pages/canvas/canvas_activities_page.rb, pages/canvas/canvas_page.rb, pages/junction/api_academics_roster_page.rb, pages/junction/canvas_e_grades_export_page.rb, settings.yml, spec/junction/canvas_lti_e_grades_export_spec.rb, util/utils.rb
E-Grades test now compares each CSV row to the corresponding gradebook total score.  Supports both the Beta and Test versions of the gradebook.
=> Part one of e-grades test upgrade

pages/boac/api_user_analytics_page.rb, pages/boac/boac_pages.rb, pages/boac/cohort_list_view_page.rb, pages/boac/cohort_page.rb, pages/boac/home_page.rb, pages/boac/student_page.rb, spec/boac/boac_custom_cohort_spec.rb, spec/boac/boac_team_member_data_spec.rb, spec/boac/boac_user_search_and_my_list_spec.rb, util/boac_utils.rb
Main changes: 
- adapt to new course listings on student pages
- add coverage for inactive and intensive cohorts
=> Test updates for BOAC v1.2

pages/cal_net_page.rb, pages/canvas/canvas_activities_page.rb, pages/canvas/canvas_page.rb, pages/junction/api_academics_roster_page.rb, pages/junction/canvas_e_grades_export_page.rb, spec/junction/canvas_lti_e_grades_api_spec.rb, spec/junction/canvas_lti_e_grades_export_spec.rb
- Splits the tests for grade accuracy into their own script, rather than adding to the existing script (too complicated)
- Dumps support for new gradebook UI until we actually use it
=> E-Grades Export tests part 2

pages/cal_net_page.rb, pages/page.rb, spec/junction/canvas_lti_course_captures_spec.rb, spec/junction/canvas_lti_e_grades_export_spec.rb, util/lrs_utils.rb
Fixes CAS authentication in test scripts, plus misc other minor fixes.
=> Fix CAS auth

pages/boac/api_user_analytics_page.rb, pages/boac/cohort_list_view_page.rb, pages/boac/student_page.rb, spec/boac/boac_custom_cohort_spec.rb, spec/boac/boac_team_member_data_spec.rb
ASC test updates:
- Adds tests to compare Canvas API stats to Data Loch stats
- Fixes broken tests
- Adds a few misc tests
=> BOAC analytics tests

models/canvas/assignment.rb, pages/canvas/canvas_activities_page.rb, pages/canvas/canvas_page.rb, pages/junction/canvas_e_grades_export_page.rb, pages/page.rb, scripts/lrs_canvas_events_assignments_script.rb, spec/boac/boac_team_analytics_data_spec.rb, spec/junction/canvas_lti_e_grades_api_spec.rb, spec/lrs/lrs_events_assignments_spec.rb, spec/suitec/canvas_assignment_submissions_spec.rb, spec/suitec/canvas_assignment_sync_spec.rb
Initial tests to compare assignment data visible to students in their course sites with the corresponding data presented in BOAC
=> Tests for loch assignments

pages/canvas/canvas_announce_discuss_page.rb, pages/canvas/canvas_assignments_page.rb, settings.yml, spec/boac/boac_team_analytics_data_spec.rb, util/boac_utils.rb
Better handling of discussion assignments, screenshots are optional, and Loch vs Canvas API comparisons are ditched for "scores".
=> Misc assignment analytics test fixes

pages/boac/boac_pages.rb, pages/boac/cohort_pages.rb, pages/boac/curated_cohort_list_view_page.rb, pages/boac/curated_cohort_page.rb, pages/boac/filtered_cohort_page.rb, pages/boac/home_page.rb, pages/boac/student_page.rb, pages/page.rb, spec/boac/boac_curated_cohort_spec.rb, spec/boac/boac_filtered_cohort_spec.rb, spec/boac/boac_navigation_spec.rb, spec/boac/boac_team_analytics_data_spec.rb, spec/boac/boac_team_sis_data_spec.rb
Includes:
- Adapting existing tests to numerous v2.1 UX changes
- Updating the filtered cohort script to cover the ASC, non-ASC, and admin flavors of cohort search
A significant part of the diff in the SIS data test script is changed indent.
=> BOAC test updates for v2.1

pages/boac/filtered_cohort_page.rb, pages/canvas/canvas_assignments_page.rb, spec/boac/boac_filtered_cohort_spec.rb
- Fix assignment submission count test
- Write filtered cohort search performance to CSV
=> Small tweaks to BOAC tests

pages/boac/api_user_analytics_page.rb, pages/boac/filtered_cohort_page.rb, pages/boac/student_page.rb, pages/canvas/canvas_assignments_page.rb, pages/junction/canvas_e_grades_export_page.rb, settings.yml, spec/boac/boac_team_analytics_data_spec.rb, util/boac_utils.rb, util/utils.rb
- Fixes how assignment submission status is determined in the Canvas UI
- Allows new Chrome profiles to be used in tests (so Teena can play nice with her sisters)
- Adapts to the new BOAC analytics API structure and content
- Has filtered cohort search tests record the performance of the search
=> Fixes for assignment counts, Chrome profile, and analytics API structure

pages/boac/api_user_analytics_page.rb, pages/boac/boac_pages.rb, pages/boac/filtered_cohort_page.rb, pages/boac/student_page.rb, pages/canvas/canvas_grades_page.rb, pages/canvas/canvas_page.rb, pages/junction/canvas_e_grades_export_page.rb, pages/oec/blue_page.rb, settings.yml, spec/boac/boac_curated_cohort_spec.rb, spec/boac/boac_filtered_cohort_spec.rb, spec/boac/boac_team_assignments_data_spec.rb, spec/boac/boac_team_class_pages_spec.rb, spec/boac/boac_team_last_activity_spec.rb, spec/junction/canvas_lti_e_grades_api_spec.rb, spec/oec/oec_form_fill_out_spec.rb, spec/suitec/asset_library_pins_spec.rb, test_data/test-data-boac.json, util/boac_utils.rb, util/oec_utils.rb
BOAC:
- Added configuration for which team or dept to use in specific tests scripts.  Also added config to set max number of students to test for running long looping scripts.
- More last activity tests and misc fixes.
JUNCTION
- Prevent error with a single user from derailing the scripts.
OEC
- Support new question type
- Log more info about test results
=> BOAC, OEC, Junction test updates

pages/canvas/canvas_grades_page.rb, settings.yml, spec/boac/boac_alerts_spec.rb, spec/boac/boac_filtered_cohort_spec.rb, spec/junction/canvas_lti_e_grades_api_spec.rb, util/nessie_utils.rb, util/oec_utils.rb
BOAC:
- add connection to RDS instance
- rework alerts test to handle no-alerts-present
Junction:
- tweaks to E-Grades tests
OEC:
- avoid CALTEACH for now
=> Multiple fixes

pages/boac/api_user_analytics_page.rb, settings.yml, spec/boac/boac_filtered_cohort_spec.rb, spec/boac/boac_team_assignments_data_spec.rb, spec/boac/boac_team_class_pages_spec.rb, spec/boac/boac_team_sis_data_spec.rb, util/boac_utils.rb
- Small improvements to test configs
- Better management of test data file for cohort search tests
- Remove redundant alerts tests
=> Small config tweaks for BOAC tests

pages/canvas/canvas_page.rb, pages/junction/api_academics_course_provision_page.rb, settings.yml, spec/boac/boac_team_sis_data_spec.rb, util/boac_utils.rb, util/nessie_utils.rb, util/utils.rb
Temporarily adds config for student data source (old BOAC tables vs new Nessie tables) to allow Prod vs Dev testing.  Eventually BOAC tables will go away.
Bonus: minor fixes for Junction and SuiteC tests.
=> Switch to Nessie student data source

pages/boac/api_user_analytics_page.rb, pages/boac/boac_pages.rb, pages/boac/filtered_cohort_page.rb, pages/canvas/canvas_assignments_page.rb, pages/junction/canvas_e_grades_export_page.rb, settings.yml, spec/boac/boac_alerts_spec.rb, spec/boac/boac_filtered_cohort_spec.rb, spec/boac/boac_navigation_spec.rb, spec/boac/boac_team_class_pages_spec.rb, spec/boac/boac_team_sis_data_spec.rb, util/boac_utils.rb
- Save screenshots if tests error out in headless mode
- A bit more search performance data
- Speed up assignments / grades tests
- Work around a couple BOAC bugs
=> Better BOAC test logging, misc fixes

pages/boac/api_user_analytics_page.rb, scripts/boac_cohort_filter_performance_script.rb, scripts/boac_user_data_script.rb, spec/boac/boac_user_role_coe_spec.rb, util/nessie_utils.rb
Plus a couple misc test fixes.
=> Scripts to collect BOAC's SIS data and search performance data

pages/boac/api_user_analytics_page.rb, pages/boac/boac_pages.rb, pages/boac/filtered_cohort_matrix_page.rb, pages/boac/filtered_cohort_page.rb, pages/canvas/canvas_assignments_page.rb, pages/page.rb, settings.yml, spec/boac/boac_curated_cohort_spec.rb, spec/boac/boac_filtered_cohort_spec.rb, spec/boac/boac_navigation_spec.rb, spec/boac/boac_user_role_asc_spec.rb, spec/boac/boac_user_role_coe_spec.rb, spec/suitec/canvas_assignment_submissions_spec.rb, util/boac_utils.rb
Misc fixes for handling CoE advisors and for measuring app performance.
=> Final test fixes for boac v2.4

.rvmrc, settings.yml
=> NOJIRA, force rvm use 2.3.4

models/boac/boac_test_config.rb, pages/boac/boac_pages.rb, pages/boac/filtered_cohort_page.rb, spec/boac/boac_filtered_cohort_spec.rb, spec/boac/boac_user_role_coe_spec.rb
Just a couple boo-boos wreak lotsa havoc.
=> Fix BOAC tests

pages/boac/cohort_pages.rb, pages/boac/filtered_cohort_page.rb, spec/boac/boac_user_role_admin_spec.rb, spec/boac/boac_user_role_asc_spec.rb, spec/boac/boac_user_role_coe_spec.rb
https://jira.ets.berkeley.edu/jira/browse/BOAC-1269
See BOAC change https://github.com/ets-berkeley-edu/boac/pull/891
=> BOAC-1269, Teena must look for new label: 'Units Completed'

models/lti_tools.rb, pages/canvas/canvas_announce_discuss_page.rb, pages/canvas/canvas_assignments_page.rb, pages/canvas/canvas_page.rb, settings.yml, spec/lrs/lrs_events_assignments_spec.rb, spec/lrs/lrs_events_discussions_spec.rb, spec/lrs/lrs_events_enrollments_spec.rb, spec/lrs/lrs_events_groups_spec.rb, util/lrs_utils.rb
Misc fixes to get the LRS test scripts running again.
=> Resurrect LRS tests

pages/boac/api_section_page.rb, pages/boac/boac_pages.rb, pages/boac/search_results_page.rb, pages/boac/user_list_pages.rb, pages/oec/blue_page.rb, pages/page.rb, scripts/oec_data_source_script.rb, settings.yml, spec/boac/boac_class_pages_spec.rb, spec/boac/boac_filtered_cohort_spec.rb, spec/boac/boac_last_activity_spec.rb, spec/boac/boac_user_search_spec.rb, util/boac_utils.rb, util/nessie_utils.rb
A little of everything...
- Basic tests for class search
- Improvements to tests for Caliper last activity data
- A couple OEC script fixes
=> Class search, more last activity, OEC

pages/boac/boac_student_page.rb, spec/boac/boac_last_activity_spec.rb
Everything except curated cohorts and waitlisted classes.
=> New element locators for student page in Vue

spec/junction/canvas_lti_rosters_spec.rb
The workflow was not quite right.
=> Small fix to add-user Junction script

models/boac/boac_test_config.rb, pages/boac/boac_student_page.rb, settings.yml, spec/boac/boac_alerts_spec.rb, spec/boac/boac_assignments_data_spec.rb, spec/boac/boac_class_pages_spec.rb, spec/boac/boac_curated_group_spec.rb, spec/boac/boac_filtered_cohort_spec.rb, spec/boac/boac_last_activity_spec.rb, spec/boac/boac_navigation_spec.rb, spec/boac/boac_team_sis_data_spec.rb, spec/boac/boac_user_role_admin_spec.rb, spec/boac/boac_user_role_asc_spec.rb, spec/boac/boac_user_role_coe_spec.rb, spec/boac/boac_user_search_spec.rb, util/utils.rb
Allows toggling between Chrome profiles for BOAC test runs.  Also a few other minor test fixes.
=> [QA] Fix Chrome profile Vue problems

models/boac/boac_test_config.rb, settings.yml, spec/boac/boac_alerts_spec.rb, spec/boac/boac_assignments_data_spec.rb, spec/boac/boac_class_pages_spec.rb, spec/boac/boac_curated_group_spec.rb, spec/boac/boac_filtered_cohort_spec.rb, spec/boac/boac_last_activity_spec.rb, spec/boac/boac_navigation_spec.rb, spec/boac/boac_sis_data_spec.rb, spec/boac/boac_user_role_admin_spec.rb, spec/boac/boac_user_role_asc_spec.rb, spec/boac/boac_user_role_coe_spec.rb, spec/boac/boac_user_search_spec.rb, util/utils.rb
Master version of https://github.com/ets-berkeley-edu/ets-qa/pull/216/files
=> Fix Chrome profile Vue problems

pages/boac/boac_add_curated_selector_pages.rb, pages/boac/boac_cohort_pages.rb, pages/boac/boac_curated_group_page.rb, pages/boac/boac_filtered_cohort_page.rb, pages/boac/boac_pages.rb
https://jira.ets.berkeley.edu/jira/browse/BOAC-1649
The relevant PR in BOAC-land: https://github.com/ets-berkeley-edu/boac/pull/1165
=> BOAC-1649, curated/cohort id fixes to match latest Vue work in BOAC

pages/boac/boac_add_curated_modal_pages.rb, pages/boac/boac_cohort_pages.rb, pages/boac/boac_curated_group_page.rb, pages/boac/boac_filtered_cohort_page.rb, pages/boac/boac_student_page.rb
https://jira.ets.berkeley.edu/jira/browse/BOAC-1649
BOAC PR is https://github.com/ets-berkeley-edu/boac/pull/1168
=> BOAC-1649, ids in /cohort and /curated modals are in sync for easier qa

pages/boac/boac_filtered_cohort_page.rb, settings.yml, spec/boac/boac_last_activity_spec.rb, spec/boac/boac_sis_data_spec.rb, util/boac_utils.rb
FYI: half the diff is an indent change.
=> Fixes for last activity, SIS data, and cohort tests

models/boac/boac_departments.rb, models/boac/boac_test_config.rb, models/boac/boac_user.rb, spec/boac/boac_user_role_asc_spec.rb, spec/boac/boac_user_role_coe_spec.rb, spec/boac/boac_user_search_spec.rb, util/nessie_utils.rb
- Makes dept-specific student attributes a little easier to manage
- Supports Dept of Physics in tests
=> Boac physics

pages/boac/boac_list_view_pages.rb, spec/boac/boac_class_pages_spec.rb, util/utils.rb
Adapts to new pagination for cohorts and class pages. Also ignores some spurious JS errors.
=> Handle new pagination UI

pages/boac/boac_cohort_pages.rb, pages/boac/boac_filtered_cohort_page.rb, pages/boac/boac_user_list_pages.rb, spec/boac/boac_filtered_cohort_spec.rb, spec/boac/boac_navigation_spec.rb, spec/boac/boac_user_role_admin_spec.rb, util/utils.rb
Fix remaining list sorting failures, overlapping matrix bubble errors, and a couple workflow timing issues.
=> Final Boa 2.13 test fixes

models/boac/boac_test_config.rb, pages/boac/boac_api_admin_page.rb, pages/boac/boac_api_section_page.rb, pages/boac/boac_api_student_page.rb, pages/boac/boac_cohort_pages.rb, pages/boac/boac_filtered_cohort_page.rb, pages/boac/boac_group_page.rb, pages/boac/boac_list_view_pages.rb, pages/boac/boac_search_results_page.rb, settings.yml, spec/boac/boac_curated_group_spec.rb, spec/boac/boac_user_role_asc_spec.rb, spec/boac/boac_user_role_coe_spec.rb, util/boac_utils.rb
https://jira.ets.berkeley.edu/jira/browse/BOAC-1844
Corresponding BOAC PR: https://github.com/ets-berkeley-edu/boac/pull/1331
=> BOAC-1844, inactive students are no longer excluded from search/cohort results

pages/boac/boac_api_student_page.rb, pages/boac/boac_cohort_pages.rb, pages/boac/boac_list_view_pages.rb, pages/boac/boac_student_page.rb, pages/boac/boac_user_list_pages.rb, scripts/boac_user_data_script.rb, spec/boac/boac_class_pages_spec.rb, spec/boac/boac_last_activity_spec.rb, spec/boac/boac_navigation_spec.rb, spec/boac/boac_sis_data_spec.rb
- Create test coverage for min/max/term units
- Fix broken element locators
- Make some test script variable  and method names clearer
=> BOAC test fixes

pages/boac/boac_filtered_cohort_page.rb, pages/boac/boac_group_page.rb, pages/boac/boac_list_view_pages.rb, pages/boac/boac_student_page.rb, spec/boac/boac_curated_group_spec.rb, spec/boac/boac_sis_data_spec.rb, spec/boac/boac_user_role_asc_spec.rb, spec/boac/boac_user_role_coe_spec.rb, spec/boac/boac_user_role_physics_spec.rb, util/boac_utils.rb, util/nessie_utils.rb
- More element locator updates
- Sequence of group tests fixed
- Changed UI for null SIS data values
- Get hold data from Redshift rather than Boa PG
=> More test fixes for Boa v2.14

models/boac/boac_test_config.rb, pages/boac/boac_student_page.rb, spec/boac/boac_advising_notes_spec.rb, util/boac_utils.rb
https://jira.ets.berkeley.edu/jira/browse/BOAC-1954
Many TODOs remain.
=> BOAC-1954, verify dept advisor can create note

pages/boac/boac_student_page.rb, spec/boac/boac_advising_notes_spec.rb, spec/boac/boac_legacy_notes_spec.rb
https://jira.ets.berkeley.edu/jira/browse/BOAC-1911
Verifies work in https://github.com/ets-berkeley-edu/boac/pull/1386
=> BOAC-1911, note owner edits note and then admin deletes it

pages/canvas/canvas_page.rb, pages/suitec/asset_library_detail_page.rb, pages/suitec/asset_library_manage_assets_page.rb, pages/suitec/whiteboard_page.rb, spec/suitec/engagement_index_spec.rb
- Browser pop-ups are now appearing as alerts instead of confirmations
- Canvas changed its "unauthorized" message
=> Small fixes for SuiteC tests

models/boac/note.rb, pages/boac/boac_student_page.rb, spec/boac/boac_advising_notes_spec.rb, spec/boac/boac_legacy_notes_spec.rb, util/boac_utils.rb
Basic tests for creating, editing, and deleting advising notes, with many TODOs.
=> Tests for create, edit, delete notes

models/course.rb, pages/boac/boac_student_page.rb, pages/canvas/canvas_grades_page.rb, pages/suitec/engagement_index_page.rb, pages/suitec/whiteboard_list_view_page.rb, pages/suitec/whiteboard_page.rb, settings.yml, spec/boac/boac_advising_notes_spec.rb, spec/boac/boac_legacy_notes_spec.rb, spec/junction/canvas_lti_course_site_creation_spec.rb, spec/junction/canvas_lti_e_grades_api_spec.rb, spec/junction/canvas_lti_official_sections_spec.rb, util/boac_utils.rb, util/junction_utils.rb, util/utils.rb
- Add more tests for new Boa advising notes
- Modify driver behavior to that SuiteC tests can run on Firefox as a fallback browser
- Improve how Junction tests manage their test data
=> More tests for advising notes

teena.sh
https://jira.ets.berkeley.edu/jira/browse/BOAC-1998
* Removed ` --no-color` cuz color is pretty, no?
* Is it okay for shell script to live in base dir? I.e., the dir from which you typically run rake tasks. It can move.
=> BOAC-1998, Teena shell script prompts you for tool, version, test

README.md, pages/boac/boac_api_student_page.rb, pages/boac/boac_search_results_page.rb, pages/boac/boac_student_page.rb, pages/canvas/canvas_grades_page.rb, spec/boac/boac_advising_notes_spec.rb, spec/boac/boac_assignments_data_spec.rb, spec/boac/boac_legacy_notes_spec.rb, spec/boac/boac_sis_data_spec.rb, spec/junction/canvas_lti_e_grades_api_spec.rb, spec/junction/canvas_lti_rosters_spec.rb, util/boac_utils.rb, util/nessie_utils.rb
=> Test fixes for Boa and Junction

pages/boac/boac_class_list_view_page.rb, pages/boac/boac_search_results_page.rb, teena.sh
https://jira.ets.berkeley.edu/jira/browse/BOAC-1998
Goes along with BOAC PR https://github.com/ets-berkeley-edu/boac/pull/1410
=> BOAC-1998, teena.sh enhancements; id refs for search results view

pages/boac/boac_student_page.rb, spec/boac/boac_advising_notes_spec.rb
https://jira.ets.berkeley.edu/jira/browse/BOAC-2026
=> Fixing advising notes tests

pages/boac/boac_search_results_page.rb, spec/boac/boac_class_pages_spec.rb
https://jira.ets.berkeley.edu/jira/browse/BOAC-2136
I know this isn't the most impressive update, but I'm new in the neighborhood.
=> BOAC-2136 Test class search by partial course codes

models/boac/boac_test_config.rb, pages/boac/boac_filtered_cohort_page.rb, pages/boac/boac_search_results_page.rb, pages/boac/boac_user_list_pages.rb, pages/junction/canvas_rosters_page.rb, settings.yml, spec/boac/boac_note_content_spec.rb, test_data/test-data-boac-l-and-s.json, util/nessie_utils.rb, util/suite_c_utils.rb
Including:
- Different Boa sorting logic for user lists vs list view
- More restrictive cohort filters for huge L&S student population
- CoE gender filter
=> Misc test fixes

pages/boac/boac_student_page_advising_note.rb, settings.yml, spec/boac/boac_note_content_spec.rb, spec/boac/boac_note_mgmt_spec.rb, spec/boac/boac_user_role_l_and_s_spec.rb, util/nessie_utils.rb
- Exclude L&S by default in order to test Boa/Nessie release candidate
- Add tests for note permalinks
=> Exclude L&S

pages/boac/boac_admin_page.rb, spec/boac/boac_user_role_admin_spec.rb, spec/boac/boac_user_role_asc_spec.rb, spec/boac/boac_user_role_coe_spec.rb, spec/boac/boac_user_role_l_and_s_spec.rb, spec/boac/boac_user_role_physics_spec.rb
https://jira.ets.berkeley.edu/jira/browse/BOAC-2182
More service-alert tests are coming soon.
=> BOAC-2182, Admin page tests, including initial service alert test

pages/boac/boac_pages.rb, spec/boac/boac_note_mgmt_spec.rb
https://jira.ets.berkeley.edu/jira/browse/BOAC-2197
The apprenticeship continues.
=> BOAC-2197 Tests for search filter on note author

pages/boac/boac_pages.rb, spec/boac/boac_curated_group_spec.rb
- Fix broken locator for sidebar cohorts/groups
- Add explicit tests for group list view membership for each group in the test script
=> Fix groups tests

pages/boac/boac_admin_page.rb, pages/boac/boac_cohort_pages.rb, spec/boac/boac_user_role_admin_spec.rb
https://jira.ets.berkeley.edu/jira/browse/BOAC-2182
More ids in BOA PR https://github.com/ets-berkeley-edu/boac/pull/1532
=> BOAC-2182, BOA service announcement tests (unpost, edit, post again)

models/boac/boac_departments.rb, models/boac/boac_test_config.rb, pages/boac/boac_class_list_view_page.rb, pages/boac/boac_cohort_pages.rb, pages/boac/boac_filtered_cohort_page.rb, pages/boac/boac_group_modal_pages.rb, pages/boac/boac_search_results_page.rb, pages/boac/boac_student_page.rb, pages/boac/boac_student_page_advising_note.rb, pages/boac/boac_user_list_pages.rb, spec/boac/boac_note_content_spec.rb, util/nessie_utils.rb
Misc fixes, including an XPath bloodbath.
=> BOA test fixes

pages/boac/boac_pages.rb, pages/boac/boac_search_results_page.rb, spec/boac/boac_search_spec.rb
https://jira.ets.berkeley.edu/jira/browse/BOAC-2269
With assorted other fixes for broken or outdated parts of the tests.
=> BOAC-2269 Date filters on note search

pages/boac/boac_list_view_pages.rb, pages/boac/boac_pages.rb, pages/boac/boac_search_results_page.rb, pages/boac/boac_student_page.rb, spec/boac/boac_sis_data_spec.rb, spec/boac/boac_user_role_asc_spec.rb, spec/boac/boac_user_role_coe_spec.rb, spec/boac/boac_user_role_l_and_s_spec.rb, spec/boac/boac_user_role_physics_spec.rb, util/spec_helper.rb
https://jira.ets.berkeley.edu/jira/browse/BOAC-2399
https://jira.ets.berkeley.edu/jira/browse/BOAC-2400
PR on the BOA side: https://github.com/ets-berkeley-edu/boac/pull/1653
=> BOAC-2399, fix 'waitlisted-for-...' ref; prep for encoded student URI when demo-mode

pages/boac/boac_class_list_view_page.rb, pages/boac/boac_pages.rb, pages/boac/boac_search_results_page.rb, spec/boac/boac_search_spec.rb
Fixes some note search tests and some locators for Canvas assignment data.
=> Further BOA test fixes for v2.19

models/boac/boac_test_config.rb, pages/boac/boac_api_student_page.rb, pages/boac/boac_filtered_cohort_page.rb, spec/boac/boac_class_pages_spec.rb, spec/boac/boac_curated_group_spec.rb, spec/boac/boac_filtered_cohort_spec.rb, spec/boac/boac_last_activity_spec.rb, spec/boac/boac_note_content_spec.rb, spec/boac/boac_note_mgmt_spec.rb, spec/boac/boac_search_spec.rb, spec/boac/boac_user_role_asc_spec.rb, spec/boac/boac_user_role_coe_spec.rb, spec/boac/boac_user_role_l_and_s_spec.rb, spec/boac/boac_user_role_physics_spec.rb
https://jira.ets.berkeley.edu/jira/browse/BOAC-2404
=> BOAC-2404 Test fixes including desiloing

pages/boac/boac_pages.rb, settings.yml, spec/boac/boac_search_spec.rb, util/nessie_utils.rb
https://jira.ets.berkeley.edu/jira/browse/BOAC-2268
=> BOAC-2268 Tests for note search advisor name filter

models/boac/boac_test_config.rb, pages/boac/boac_filtered_cohort_page.rb, spec/boac/boac_assignments_data_spec.rb, spec/boac/boac_class_pages_spec.rb, spec/boac/boac_curated_group_spec.rb, spec/boac/boac_filtered_cohort_spec.rb, spec/boac/boac_last_activity_spec.rb, spec/boac/boac_navigation_spec.rb, spec/boac/boac_note_batch_spec.rb, spec/boac/boac_note_content_spec.rb, spec/boac/boac_note_mgmt_spec.rb, spec/boac/boac_search_spec.rb, spec/boac/boac_sis_data_spec.rb, spec/boac/boac_user_role_admin_spec.rb, spec/boac/boac_user_role_asc_spec.rb, spec/boac/boac_user_role_coe_spec.rb, spec/boac/boac_user_role_l_and_s_spec.rb, spec/boac/boac_user_role_physics_spec.rb
Vacuums up some cruft.  Next job will be to collapse the various user_role scripts into one to speed execution.
=> Minor post-de-silo-ing cleanup

models/boac/boac_departments.rb, models/boac/boac_test_config.rb, pages/boac/boac_admin_page.rb, pages/boac/boac_filtered_cohort_page.rb, pages/boac/boac_pages.rb, spec/boac/boac_filtered_cohort_spec.rb, spec/boac/boac_user_role_admin_spec.rb, spec/boac/boac_user_role_asc_spec.rb, spec/boac/boac_user_role_coe_spec.rb, spec/boac/boac_user_role_l_and_s_spec.rb, spec/boac/boac_user_role_physics_spec.rb, test_data/test-data-boac.json
- tests for BOA user CSV export
- further reductions in cohort sizes for filtered cohort tests
=> Tests for admin CSV export plus misc fixes

models/boac/boac_test_config.rb, models/boac/cohort_filter.rb, pages/boac/boac_filtered_cohort_page.rb, spec/boac/boac_filtered_cohort_spec.rb, spec/boac/boac_user_role_admin_spec.rb, spec/boac/boac_user_role_asc_spec.rb, spec/boac/boac_user_role_coe_spec.rb, spec/boac/boac_user_role_l_and_s_spec.rb, spec/boac/boac_user_role_physics_spec.rb, test_data/test-data-boac.json
https://jira.ets.berkeley.edu/jira/browse/BOAC-2457
I also changed `advisorLdapUids` to `coeAdvisorLdapUids` due to https://github.com/ets-berkeley-edu/boac/pull/1728
=> BOAC-2457, the ol' gender is now coe_gender

models/boac/boac_test_config.rb, models/boac/cohort_filter.rb, pages/boac/boac_filtered_cohort_page.rb, spec/boac/boac_filtered_cohort_spec.rb, spec/boac/boac_user_role_admin_spec.rb, spec/boac/boac_user_role_asc_spec.rb, spec/boac/boac_user_role_coe_spec.rb, spec/boac/boac_user_role_l_and_s_spec.rb, spec/boac/boac_user_role_physics_spec.rb, test_data/test-data-boac.json
https://jira.ets.berkeley.edu/jira/browse/BOAC-2256
Corresponding BOA change: ets-berkeley-edu/boac#1731
BOA's ethnicity-for-all filter is coming soon.
=> BOAC-2256, cohort filter 'ethnicity' is now 'coeEthnicity'

models/boac/boac_test_config.rb, models/boac/cohort_filter.rb, pages/boac/boac_filtered_cohort_page.rb, scripts/boac_cohort_filter_performance_script.rb, spec/boac/boac_class_pages_spec.rb, spec/boac/boac_curated_group_spec.rb, spec/boac/boac_filtered_cohort_spec.rb, spec/boac/boac_note_batch_spec.rb, spec/boac/boac_sis_data_spec.rb, spec/boac/boac_user_role_admin_spec.rb, spec/boac/boac_user_role_asc_spec.rb, spec/boac/boac_user_role_coe_spec.rb, spec/boac/boac_user_role_l_and_s_spec.rb, spec/boac/boac_user_role_physics_spec.rb, test_data/test-data-boac.json, util/nessie_utils.rb
https://jira.ets.berkeley.edu/jira/browse/BOAC-2471
=> BOAC-2471 Tests for 'My Students' filter

models/boac/boac_test_config.rb, pages/boac/boac_group_page.rb, settings.yml, spec/boac/boac_sis_data_spec.rb, util/boac_utils.rb
Teena's fed up testing the same students over and over and wants the option to meet new people.  This also requires changes to the way the SIS data script obtains its pool of test students.
=> Vary test students

models/boac/boac_test_config.rb, models/boac/cohort_filter.rb, pages/boac/boac_api_student_page.rb, pages/boac/boac_cohort_pages.rb, pages/boac/boac_filtered_cohort_page.rb, pages/boac/boac_user_list_pages.rb, spec/boac/boac_filtered_cohort_spec.rb, test_data/test-data-boac.json, util/nessie_utils.rb
- URM and ethnicity filters
- fixes for list view sorting tests
=> New filter tests plus fixes

models/boac/boac_departments.rb, models/boac/boac_test_config.rb, pages/boac/boac_api_section_page.rb, pages/boac/boac_student_page.rb, spec/boac/boac_user_role_notes_only_spec.rb, util/nessie_utils.rb
https://jira.ets.berkeley.edu/jira/browse/BOAC-2515
As an aside, no more physics schema.
=> BOAC-2515 Tests for notes-only user role

models/boac/boac_test_config.rb, models/boac/boac_user.rb, pages/boac/boac_student_page_advising_note.rb, spec/boac/boac_note_content_spec.rb, spec/boac/boac_search_spec.rb, util/boac_utils.rb
https://jira.ets.berkeley.edu/jira/browse/BOAC-2580
=>  BOAC-2580 Tests for note search within academic timeline

pages/canvas/canvas_page.rb, spec/junction/canvas_lti_project_site_creation_spec.rb
=> Fix Canvas user role picker tests

pages/boac/boac_student_page.rb, spec/boac/boac_note_content_spec.rb, spec/boac/boac_search_spec.rb, util/nessie_utils.rb
Plus a couple other test fixes.
=> Handle E&I notes in tests

spec/boac/boac_note_content_spec.rb, spec/boac/boac_search_spec.rb, util/boac_utils.rb
Mostly indent changes, so w=1.
=> BOA test fixes just keep coming

util/utils.rb
To avoid "Cannot call non W3C standard command while in W3C mode"
=> NOJIRA, w3c=false for WebDriver::Chrome init

models/boac/cohort_filter.rb, pages/boac/boac_filtered_cohort_page_filters.rb, pages/boac/boac_filtered_cohort_page_results.rb, test_data/test-data-boac.json, util/nessie_utils.rb
Handle new filter, plus some fixes to her searchable-student-data guts.
=> Teena gets midpoint deficient grades

pages/boac/boac_pages_create_note_modal.rb
https://jira.ets.berkeley.edu/jira/browse/BOAC-2450
=> BOAC-2450, no more 'Add topic' button for Teena to click

util/nessie_utils.rb
Key user data structure by SID from the get-go instead of repeatedly combing through an array.
=> Speed up initial searchable data generation

pages/boac/boac_api_student_page.rb, pages/boac/boac_student_page.rb, scripts/boac_user_data_script.rb, spec/boac/boac_sis_data_spec.rb
https://jira.ets.berkeley.edu/jira/browse/BOAC-2630
Gotta start somewhere. Also fix a couple of miscellaneous test breakages.
=> BOAC-2630 Start adapting to inactive plan display

pages/boac/boac_api_student_page.rb, pages/boac/boac_class_list_view_page.rb, spec/boac/boac_class_pages_spec.rb
https://jira.ets.berkeley.edu/jira/browse/BOAC-2630
=> BOAC-2630 Graduated students on class pages

pages/boac/boac_group_page.rb, spec/boac/boac_curated_group_spec.rb, util/nessie_utils.rb
Includes removal of inactive students for now.
=> Test updates for v3.2

spec/boac/boac_sis_data_spec.rb
https://jira.ets.berkeley.edu/jira/browse/BOAC-2729
=> BOAC-2729 Fix test failures on graduated students

pages/boac/boac_cohort_pages.rb, pages/boac/boac_student_page.rb, spec/boac/boac_sis_data_spec.rb
https://jira.ets.berkeley.edu/jira/browse/BOAC-2732
=> BOAC-2732 Tests for graduated student degree display

pages/boac/boac_class_list_view_page.rb, pages/boac/boac_cohort_pages.rb, pages/boac/boac_student_page.rb, spec/boac/boac_class_pages_spec.rb, spec/boac/boac_sis_data_spec.rb
https://jira.ets.berkeley.edu/jira/browse/BOAC-2731
=> BOAC-2731 Tests for inactive status label

pages/boac/boac_api_student_page.rb, pages/boac/boac_cohort_pages.rb, spec/boac/boac_sis_data_spec.rb
https://jira.ets.berkeley.edu/jira/browse/BOAC-2768
=> BOAC-2768 Tests for waitlist indicator on cohort/group pages

models/boac/boac_departments.rb, models/boac/boac_test_config.rb, pages/boac/boac_group_page.rb, pages/boac/boac_list_view_pages.rb, pages/boac/boac_pages.rb, spec/boac/boac_curated_group_spec.rb, spec/boac/boac_user_role_admin_spec.rb, spec/boac/boac_user_role_advisor_spec.rb, util/boac_utils.rb
https://jira.ets.berkeley.edu/jira/browse/BOAC-2726
=> BOAC-2726 Update tests for user roles and permissions

models/boac/cohort_filter.rb, pages/boac/boac_filtered_cohort_page_filters.rb, spec/boac/boac_user_role_admin_spec.rb, spec/boac/boac_user_role_advisor_spec.rb, spec/boac/boac_user_role_notes_only_spec.rb, test_data/test-data-boac.json
https://jira.ets.berkeley.edu/jira/browse/BOAC-2629
@lyttam @paulkerschen @pfarestveit - You'll need to update your `~/.webdriver-config/test-data-boac.json` (see changes to `test-data-boac.json` below)
=> BOAC-2629, format of gpaRanges and lastNameRanges input: {min, max}

models/boac/boac_test_config.rb, pages/boac/boac_filtered_cohort_page_filters.rb, pages/boac/boac_filtered_cohort_page_results.rb, spec/boac/boac_filtered_cohort_spec.rb, test_data/test-data-boac.json
https://jira.ets.berkeley.edu/jira/browse/BOAC-2629
Partners with BOA PR https://github.com/ets-berkeley-edu/boac/pull/1928
=> BOAC-2629, BOA cohorts: gpa and last_name data structure fixes

.gitignore, load_tests/boa_locust.py, requirements.txt
https://jira.ets.berkeley.edu/jira/browse/BOAC-2716
=> BOAC-2716 Locust setup for basic BOA load testing

models/boac/boac_test_config.rb, models/boac/boac_user.rb, pages/boac/boac_filtered_cohort_page_results.rb, settings.yml, spec/boac/boac_assignments_data_spec.rb, spec/boac/boac_class_pages_spec.rb, spec/boac/boac_note_batch_spec.rb, spec/boac/boac_note_templates_spec.rb, spec/boac/boac_sis_data_spec.rb, spec/boac/boac_user_role_admin_spec.rb, spec/boac/boac_user_role_advisor_spec.rb, util/nessie_utils.rb
Removes more vestiges of the advisor silos and tries to simplify the collection of searchable student data.
=> Simplify student data collection

models/boac/boac_test_config.rb, pages/boac/boac_api_student_page.rb, pages/boac/boac_student_page.rb, pages/page.rb, pages/suitec/whiteboard_page.rb, spec/boac/boac_inactive_students_spec.rb, util/boac_utils.rb, util/nessie_utils.rb
Also includes:
- some reorganizing in NessieUtils
- an Alert handling change triggered by the Selenium upgrade.
=> Tests for non-current students in BOA

pages/boac/boac_cohort_pages.rb, pages/boac/boac_filtered_cohort_page_results.rb, spec/boac/boac_filtered_cohort_spec.rb, spec/boac/boac_user_role_admin_spec.rb, spec/boac/boac_user_role_advisor_spec.rb
Plus some user role tests I forgot to add previously.
=> Tests for sorting by Entering Term

pages/boac/boac_cohort_pages.rb, pages/boac/boac_filtered_cohort_page_results.rb, pages/boac/boac_home_page.rb, pages/page.rb, scripts/boac_cohort_filter_performance_script.rb, spec/boac/boac_filtered_cohort_spec.rb, util/nessie_utils.rb
Plus 
- a check that the "test environment" footer is visible at login
- hiding the footer to permit interaction with all page elements
=> Tests for sort by units in progress

pages/boac/boac_flight_deck_page.rb, pages/boac/boac_pages.rb, pages/boac/boac_student_page_advising_note.rb, spec/boac/boac_note_batch_spec.rb, spec/boac/boac_note_content_spec.rb, spec/boac/boac_user_mgmt_spec.rb, spec/boac/boac_user_role_advisor_spec.rb, spec/boac/boac_user_role_notes_only_spec.rb, util/utils.rb
Misc test fixes for BOA v3.4, plus a muzzle on the WARN messages the Selenium logger has been spitting out since the WebDriver upgrade.
=> Test fixes

pages/boac/boac_search_results_page.rb
https://jira.ets.berkeley.edu/jira/browse/BOAC-2938
BOA PR: https://github.com/ets-berkeley-edu/boac/pull/2048
=> BOAC-2938, new a11y-linter forced BOA to remove duplicate ids

models/boac/boac_test_config.rb, models/boac/topic.rb, pages/boac/boac_pages_create_note_modal.rb, spec/boac/boac_note_mgmt_spec.rb, spec/boac/boac_note_templates_spec.rb
Fixes https://jira.ets.berkeley.edu/jira/browse/BOAC-3009
=> Fix BOA note mgmt tests

pages/boac/boac_cohort_pages.rb, pages/boac/boac_user_list_pages.rb, scripts/boac_cohort_filter_performance_script.rb, spec/boac/boac_filtered_cohort_spec.rb, test_data/test-data-boac.json
Changes to GPA sorting labels and homepage default sorting expectations
=> Fix cohort GPA tests

pages/boac/boac_cohort_pages.rb, spec/boac/boac_curated_group_spec.rb, spec/boac/boac_filtered_cohort_spec.rb
https://jira.ets.berkeley.edu/jira/browse/BOAC-2936
=> BOAC-2936: Tests export list customizable CSV columns

models/oec/oec_departments.rb, scripts/csv_compare_script.rb
=> Script to help compare CSVs

models/boac/boac_test_config.rb, models/boac/cohort_filter.rb, pages/boac/boac_filtered_cohort_page_filters.rb, pages/boac/boac_filtered_cohort_page_results.rb, spec/boac/boac_filtered_cohort_spec.rb, test_data/test-data-boac.json, util/boac_utils.rb, util/nessie_utils.rb
https://jira.ets.berkeley.edu/jira/browse/BOAC-2928
=> BOAC-2928 Cohort filter tests: GPA (Last Term)

pages/boac/boac_student_page_advising_note.rb
Grep existing Teena code to see its usage.
=> Restore method visible_collapsed_note_data (lost to inadvertant cut-and-paste?)

pages/boac/boac_student_page_advising_note.rb, pages/boac/boac_student_page_timeline.rb
https://jira.ets.berkeley.edu/jira/browse/BOAC-3051 
Corresponding BOA PR: https://github.com/ets-berkeley-edu/boac/pull/2134
=> BOAC-3051, properly extract note id from student timeline row

pages/boac/boac_pax_manifest_page.rb, settings.yml, spec/boac/boac_user_mgmt_spec.rb
https://jira.ets.berkeley.edu/jira/browse/BOAC-2935
=> BOAC-2935: Updates tests for passenger manifest redesign

models/boac/boac_test_config.rb, pages/boac/boac_api_student_page.rb, pages/boac/boac_filtered_cohort_page_results.rb, pages/boac/boac_group_modal_pages.rb, pages/boac/boac_pages.rb, pages/boac/boac_search_results_page.rb, pages/boac/boac_student_page_advising_note.rb, pages/boac/boac_student_page_timeline.rb, spec/boac/boac_filtered_cohort_spec.rb, spec/boac/boac_sis_data_spec.rb, test_data/test-data-boac.json
Plus changes to filtered cohort tests that speed up test execution significantly.
=> Numerous BOA test fixes

pages/boac/boac_appt_intake_desk.rb, spec/boac/boac_appts_drop_in_spec.rb
https://jira.ets.berkeley.edu/jira/browse/BOAC-3096
Adds tests for assigning / un-assigning advisors, updating appointments, and undoing check-in / cancel.
=> Dropping in more tests

.gitignore, pages/canvas/canvas_grades_page.rb, pages/canvas/canvas_page.rb, pages/page.rb, spec/boac/boac_assignments_data_spec.rb, spec/junction/canvas_lti_e_grades_api_spec.rb, spec/junction/canvas_lti_e_grades_export_spec.rb
The E-Grades Export script still has a number of failures related to muting assignments, but I'm not yet sure what the expectations are for the LTI tool.
=> Adapt to new Canvas gradebook

pages/boac/boac_class_pages.rb, pages/boac/boac_home_page.rb, pages/boac/boac_pax_manifest_page.rb, settings.yml, spec/boac/boac_user_mgmt_spec.rb, util/boac_utils.rb
https://jira.ets.berkeley.edu/jira/browse/BOAC-3084
=> Pax manifest add/edit user tests

pages/boac/boac_api_student_page.rb, pages/boac/boac_student_page.rb, spec/boac/boac_sis_data_spec.rb
https://jira.ets.berkeley.edu/jira/browse/BOAC-3137
https://jira.ets.berkeley.edu/jira/browse/BOAC-3138 (first part)
=> BOAC-3137 BOAC-3138 Adapt to redesigned student page

pages/boac/boac_api_student_page.rb, pages/boac/boac_student_page.rb, spec/boac/boac_sis_data_spec.rb
https://jira.ets.berkeley.edu/jira/browse/BOAC-3138
=> BOAC-3138 Additional data elements on student profile

pages/boac/boac_student_page.rb, spec/boac/boac_appts_drop_in_spec.rb, spec/boac/boac_class_pages_spec.rb, spec/boac/boac_sis_data_spec.rb
Including https://jira.ets.berkeley.edu/jira/browse/BOAC-3152
=> BOA test fixes and improvements

pages/boac/boac_api_student_page.rb, pages/boac/boac_student_page.rb, spec/boac/boac_sis_data_spec.rb
https://jira.ets.berkeley.edu/jira/browse/BOAC-3148
=> BOAC-3148 Update tests for inactive minors

pages/canvas/canvas_assignments_page.rb, pages/canvas/canvas_grades_page.rb, pages/junction/canvas_e_grades_export_page.rb, spec/boac/boac_assignments_data_spec.rb, spec/junction/canvas_lti_course_add_user_spec.rb, spec/junction/canvas_lti_e_grades_export_spec.rb
https://jira.ets.berkeley.edu/jira/browse/CLC-7185
=> Update E-Grades Export tests

models/boac/boac_test_config.rb, models/boac/cohort_filter.rb, pages/boac/boac_filtered_cohort_page_filters.rb, pages/boac/boac_filtered_cohort_page_results.rb, spec/boac/boac_filtered_cohort_spec.rb, test_data/test-data-boac.json, util/nessie_utils.rb
https://jira.ets.berkeley.edu/jira/browse/BOAC-2929
=> Tests for BOA Visa Type filters

pages/boac/boac_cohort_pages.rb, pages/boac/boac_filtered_cohort_page_results.rb, spec/boac/boac_filtered_cohort_spec.rb, util/boac_utils.rb, util/nessie_utils.rb
https://jira.ets.berkeley.edu/jira/browse/BOAC-2932
=> BOA tests for sort-by-last-term-gpa

models/boac/appointment_status.rb, models/boac/boac_test_config.rb, pages/boac/boac_appt_intake_desk.rb, pages/boac/boac_pages.rb, pages/boac/boac_search_results_page.rb, pages/suitec/impact_studio_page.rb, settings.yml, spec/boac/boac_appts_drop_in_spec.rb, spec/boac/boac_curated_group_spec.rb, spec/boac/boac_inactive_students_spec.rb, spec/boac/boac_note_batch_spec.rb, spec/boac/boac_note_mgmt_spec.rb, spec/boac/boac_search_appt_spec.rb, spec/boac/boac_search_class_spec.rb, spec/boac/boac_search_note_spec.rb, spec/boac/boac_search_student_spec.rb, spec/boac/boac_user_role_notes_only_spec.rb, spec/lrs/lrs_events_enrollments_spec.rb, util/boac_utils.rb
https://jira.ets.berkeley.edu/jira/browse/BOAC-3151
- Adds tests for appointment searches
- Breaks the big fat search script into four readable scripts
- Speeds up test execution
=> Tests for appt searches

pages/boac/boac_pages.rb, pages/boac/boac_search_results_page.rb, spec/boac/boac_search_appt_spec.rb, spec/boac/boac_search_note_spec.rb, spec/boac/boac_search_student_spec.rb, util/boac_utils.rb
https://jira.ets.berkeley.edu/jira/browse/BOAC-2934
Plus some search-related test fixes.
=> Tests for search history

pages/boac/boac_cohort_pages.rb, pages/boac/boac_filtered_cohort_page_results.rb, pages/boac/boac_list_view_pages.rb, spec/boac/boac_filtered_cohort_spec.rb
https://jira.ets.berkeley.edu/jira/browse/BOAC-3212
Terms completed sorting to come separately.
=> Tests for reverse sorting

pages/boac/boac_cohort_pages.rb, pages/boac/boac_filtered_cohort_page_results.rb, spec/boac/boac_filtered_cohort_spec.rb, util/nessie_utils.rb
https://jira.ets.berkeley.edu/jira/browse/BOAC-3212
=> Tests for sort by terms completed

load_tests/boa_locust.py
https://jira.ets.berkeley.edu/jira/browse/BOAC-3193
=> BOAC-3193 Add drop-in waitlist polling to load tests

pages/boac/boac_flight_deck_page.rb, pages/boac/boac_pages.rb, pages/boac/boac_student_page_appointment.rb, spec/boac/boac_appts_drop_in_spec.rb, spec/boac/boac_user_mgmt_spec.rb
Some of this will need to be tweaked as the UI changes, but I wanted the tests written ahead of time.
=> Tests for toggling drop-in advisor role

spec/boac/boac_flight_data_recorder_spec.rb
https://jira.ets.berkeley.edu/jira/browse/BOAC-3258
=> Test cases for the BOA FDR

pages/boac/boac_filtered_cohort_page_results.rb
QA portion of https://jira.ets.berkeley.edu/jira/browse/BOAC-3054
=> Align BOA sorting expectations with reality

pages/boac/boac_flight_data_recorder_page.rb, spec/boac/boac_flight_data_recorder_spec.rb, util/boac_utils.rb
https://jira.ets.berkeley.edu/jira/browse/BOAC-3260
=> Final FDR tests

spec/boac/boac_filtered_cohort_spec.rb, spec/boac/boac_filtered_group_spec.rb
https://jira.ets.berkeley.edu/jira/browse/BOAC-3293
=> Test cases for curated filtered cohort groups

models/boac/advisor_role.rb, models/boac/boac_test_config.rb, models/boac/boac_user.rb, models/boac/dept_membership.rb, pages/boac/boac_pax_manifest_page.rb, spec/boac/boac_appts_drop_in_spec.rb, spec/boac/boac_flight_data_recorder_spec.rb, spec/boac/boac_note_mgmt_spec.rb, spec/boac/boac_user_mgmt_spec.rb, util/boac_utils.rb
https://jira.ets.berkeley.edu/jira/browse/BOAC-3284
=> Adapt to BOA user schema changes

models/boac/boac_test_config.rb, models/boac/cohort.rb, models/boac/cohort_filter.rb, models/boac/curated_group.rb, pages/boac/boac_filtered_cohort_page_filters.rb, pages/boac/boac_group_page.rb, pages/boac/boac_pages.rb, spec/boac/boac_filtered_cohort_spec.rb, spec/boac/boac_filtered_group_spec.rb
https://jira.ets.berkeley.edu/jira/browse/BOAC-3292
=> Tests for filtered groups

models/boac/boac_test_config.rb, models/boac/cohort_filter.rb, pages/boac/boac_filtered_cohort_page_filters.rb, pages/boac/boac_filtered_cohort_page_results.rb, spec/boac/boac_filtered_cohort_spec.rb, util/nessie_utils.rb
https://jira.ets.berkeley.edu/jira/browse/BOAC-3261 qq
=> BOAC-3261: Adds tests for College cohort filter

test_data/test-data-boac.json
https://jira.ets.berkeley.edu/jira/browse/BOAC-3261
=> BOAC-3261: Adds test data for College cohort filter

models/boac/boac_test_config.rb, pages/boac/boac_appt_intake_desk.rb, pages/boac/boac_flight_deck_page.rb, pages/boac/boac_pax_manifest_page.rb, settings.yml, spec/boac/boac_appts_drop_in_spec.rb, spec/boac/boac_user_mgmt_spec.rb, util/boac_utils.rb
https://jira.ets.berkeley.edu/jira/browse/BOAC-3365
=> More BOA drop-in tests

models/boac/boac_test_config.rb, pages/boac/boac_admit_list_pages.rb, pages/boac/boac_pages.rb, pages/boac/boac_search_results_page.rb, spec/boac/boac_search_admit_spec.rb, util/nessie_utils.rb
Part 2 of https://jira.ets.berkeley.edu/jira/browse/BOAC-3361
=> Tests for CE3 admit search

test_data/test-data-matterhorn.json
https://jira.ets.berkeley.edu/jira/browse/DIABLO-23
=> Update capture agent list

load_tests/boa_locust.py, util/boac_utils.rb
https://jira.ets.berkeley.edu/jira/browse/BOAC-3334
=> BOAC-3334 Adapt Teena to loss of cohort_filter_owners

models/boac/cohort_admit_filter.rb, pages/boac/boac_admit_list_pages.rb, pages/boac/boac_admit_page.rb, pages/boac/boac_cohort_pages.rb, pages/boac/boac_filtered_admits_page.rb, pages/boac/boac_filtered_cohort_page.rb, pages/boac/boac_filtered_cohort_page_filters.rb, pages/boac/boac_filtered_cohort_page_results.rb, pages/boac/boac_pages.rb, pages/boac/boac_search_results_page.rb, spec/boac/boac_filtered_admits_spec.rb, spec/boac/boac_search_admit_spec.rb, spec/boac/boac_sis_admit_data_spec.rb, test_data/test-data-boac.json, util/nessie_utils.rb
https://jira.ets.berkeley.edu/jira/browse/BOAC-3361
=> Tests for CE3 filters

models/boac/boac_test_config.rb, models/boac/cohort_filter.rb, pages/boac/boac_filtered_cohort_page_filters.rb, pages/boac/boac_filtered_cohort_page_results.rb, spec/boac/boac_filtered_cohort_spec.rb, test_data/test-data-boac.json, util/nessie_utils.rb
https://jira.ets.berkeley.edu/jira/browse/BOAC-3484
=> Tests for intended major filter

models/boac/boac_test_config.rb, models/boac/cohort_filter.rb, pages/boac/boac_cohort_pages.rb, pages/boac/boac_filtered_cohort_page_filters.rb, pages/boac/boac_filtered_cohort_page_results.rb, spec/boac/boac_filtered_cohort_spec.rb, test_data/test-data-boac.json, util/nessie_utils.rb
https://jira.ets.berkeley.edu/jira/browse/BOAC-3497
=> Tests for BOA minors filter

pages/canvas/canvas_grades_page.rb, pages/canvas/canvas_page.rb, pages/junction/canvas_e_grades_export_page.rb, spec/junction/canvas_lti_e_grades_export_spec.rb
https://jira.ets.berkeley.edu/jira/browse/CLC-7281
First of several PRs to align tests with new workflow and expectations.
=> Updates to E-Grades tests

pages/canvas/canvas_grades_page.rb, pages/junction/canvas_e_grades_export_page.rb, spec/boac/boac_assignments_data_spec.rb, spec/junction/canvas_lti_e_grades_api_spec.rb, spec/junction/canvas_lti_e_grades_export_spec.rb
https://jira.ets.berkeley.edu/jira/browse/CLC-7281
=> More updates to e-grades tests

scripts/oec_data_source.sh, scripts/oec_data_source_script.rb
- Adds a shell script to run the Selenium script
- Adds a headless browser option
- All three data sources can follow either data update workflow
=> OEC script

pages/boac/boac_api_student_page.rb, pages/boac/boac_pax_manifest_page.rb, pages/boac/boac_student_page.rb, spec/boac/boac_user_mgmt_spec.rb, spec/boac/boac_user_role_restricted_spec.rb, util/boac_utils.rb
https://jira.ets.berkeley.edu/jira/browse/BOAC-3507
=> More tests for note-less BOA

models/oec/oec_departments.rb
=> Missing OEC dept

models/boac/boac_test_config.rb, models/boac/note.rb, models/boac/note_source.rb, pages/boac/boac_student_page_advising_note.rb, spec/boac/boac_note_content_spec.rb, spec/boac/boac_search_note_spec.rb, spec/boac/boac_user_role_advisor_spec.rb, spec/boac/boac_user_role_director_spec.rb, spec/boac/boac_user_role_restricted_spec.rb, util/nessie_utils.rb
A big part of the change is an indent.
=> Update tests for BOA v4.7

models/boac/boac_test_config.rb, models/boac/cohort_filter.rb, pages/boac/boac_filtered_cohort_page_filters.rb, spec/boac/boac_filtered_cohort_spec.rb, test_data/test-data-boac.json, util/nessie_filter_utils.rb
First part of https://jira.ets.berkeley.edu/jira/browse/BOAC-3316
=> Tests for acad standing filter

models/boac/boac_test_config.rb, models/boac/note_template.rb, models/boac/topic.rb, pages/boac/boac_api_student_page.rb, pages/boac/boac_cohort_pages.rb, pages/boac/boac_filtered_cohort_page_filters.rb, pages/boac/boac_flight_deck_page.rb, pages/boac/boac_pages.rb, pages/boac/boac_pages_create_note_modal.rb, pages/boac/boac_student_page.rb, spec/boac/boac_appts_content_spec.rb, spec/boac/boac_appts_drop_in_spec.rb, spec/boac/boac_filtered_admits_spec.rb, spec/boac/boac_filtered_cohort_spec.rb, spec/boac/boac_topic_mgmt_spec.rb, spec/boac/boac_user_role_advisor_spec.rb, spec/boac/boac_user_role_director_spec.rb, util/boac_utils.rb, util/nessie_filter_utils.rb
Plus test fixes for academic standing and other misc fixes.
=> Tests for topic mgmt

pages/page.rb, spec/boac/boac_flight_data_recorder_spec.rb, spec/boac/boac_user_role_advisor_spec.rb, util/nessie_filter_utils.rb, util/nessie_utils.rb
=> Test coverage for cohort owner

models/course_site.rb, models/junction/junction_test_config.rb, pages/junction/canvas_course_add_user_page.rb, pages/page.rb, spec/boac/boac_appts_drop_in_spec.rb, spec/boac/boac_class_pages_spec.rb, spec/boac/boac_user_role_advisor_spec.rb, spec/junction/canvas_lti_course_add_user_spec.rb, spec/junction/canvas_lti_course_captures_spec.rb, spec/junction/canvas_lti_course_site_creation_spec.rb, spec/junction/canvas_lti_e_grades_api_spec.rb, spec/junction/canvas_lti_e_grades_export_spec.rb, spec/junction/canvas_lti_mailing_lists_spec.rb, spec/junction/canvas_lti_official_sections_spec.rb, spec/junction/canvas_lti_project_site_creation_spec.rb, spec/junction/canvas_lti_rosters_spec.rb, spec/junction/junction_background_tasks_spec.rb
=> Move Junction test script config into a central location

pages/boac/boac_add_group_selector_pages.rb
https://jira.ets.berkeley.edu/jira/browse/BOAC-1736
BOA PR is https://github.com/ets-berkeley-edu/boac/pull/2612
=> BOAC-1736, 'create-curated-group' element is now a link, not a button

pages/boac/boac_cohort_pages.rb, util/utils.rb
Plus Teena gets her own Y2K bug!
=> Fix cohort sorting tests

pages/boac/boac_add_group_selector_pages.rb, pages/boac/boac_api_student_page.rb, pages/boac/boac_cohort_pages.rb, pages/boac/boac_pagination.rb, pages/boac/boac_student_page.rb, pages/boac/boac_user_list_pages.rb, spec/boac/boac_sis_student_data_spec.rb
Accessibility, pagination, SIS data, etc changes.
=> BOA test updates

pages/boac/boac_filtered_cohort_page_filters.rb
https://jira.ets.berkeley.edu/jira/browse/BOAC-3760
Depends on PR https://github.com/ets-berkeley-edu/boac/pull/2662
=> BOAC-3760, cohort filter dropdown is now a button, not a link

pages/boac/boac_home_page.rb
https://jira.ets.berkeley.edu/jira/browse/BOAC-3473
BOA PR is https://github.com/ets-berkeley-edu/boac/pull/2670
=> BOAC-3473 (Teena), BOA sortable-groups are now buttons, not links

models/boac/boac_test_config.rb, models/boac/cohort_filter.rb, pages/boac/boac_filtered_cohort_page_filters.rb, spec/boac/boac_filtered_cohort_spec.rb, test_data/test-data-boac.json, util/nessie_filter_utils.rb
https://jira.ets.berkeley.edu/jira/browse/BOAC-2931
=> BOAC-2931 QA: add tests for Holds filter

pages/boac/boac_cohort_pages.rb, pages/boac/boac_flight_deck_page.rb, spec/boac/boac_user_role_admin_spec.rb, util/boac_utils.rb
The interactions with the Flight Deck date inputs should work, but they don't at the moment.  See BOAC-3596.
=> More tests for BOA exports

pages/boac/boac_student_page_advising_note.rb
https://jira.ets.berkeley.edu/jira/browse/BOAC-3788
The BOA PR: https://github.com/ets-berkeley-edu/boac/pull/2751
=> BOAC-3788, delete-note button now has unique element ID

pages/boac/boac_filtered_cohort_page_filters.rb, spec/boac/boac_filtered_admits_spec.rb, spec/boac/boac_filtered_cohort_spec.rb, spec/boac/boac_filtered_group_spec.rb, spec/boac/boac_user_mgmt_spec.rb, spec/boac/boac_user_role_admin_spec.rb, spec/boac/boac_user_role_advisor_spec.rb, spec/boac/boac_user_role_restricted_spec.rb
https://jira.ets.berkeley.edu/jira/browse/BOAC-3855
=> BOAC-3855, Teena update per cohort filter menu refactor; includes TODOs

.gitignore, models/boac/boac_test_config.rb, models/boac/cohort_filter.rb, pages/boac/boac_class_list_view_page.rb, pages/boac/boac_filtered_cohort_page_filters.rb, pages/boac/boac_student_page.rb, pages/junction/canvas_create_course_site_page.rb, pages/page.rb, spec/boac/boac_filtered_admits_spec.rb, spec/boac/boac_filtered_cohort_history_spec.rb, spec/boac/boac_filtered_cohort_spec.rb, spec/boac/boac_filtered_group_spec.rb, spec/boac/boac_sis_student_data_spec.rb, spec/boac/boac_user_mgmt_spec.rb, spec/boac/boac_user_role_advisor_spec.rb, spec/boac/boac_user_role_restricted_spec.rb, test_data/test-data-boac.json, util/nessie_filter_utils.rb, util/utils.rb
https://jira.ets.berkeley.edu/jira/browse/BOAC-3855
Plus assorted other small test fixes.
=> Handle changed BOA cohort filter UI

pages/boac/boac_appt_intake_desk.rb
https://jira.ets.berkeley.edu/jira/browse/BOAC-3774
See https://github.com/ets-berkeley-edu/boac/pull/2775
=> BOAC-3774, Teena: standard id for modals in BOA

pages/canvas/canvas_grades_page.rb, spec/junction/canvas_lti_e_grades_export_spec.rb
The Canvas feature flag UI has changed, and it's not worth asking Teena interact with it anymore.  She has more important things to do.
=> Fix E-Grades Export tests

pages/page.rb, spec/junction/canvas_lti_welcome_email_spec.rb
I made a boo-boo in my previous PR.
=> Fix iframe handling

pages/boac/boac_degree_check_template_page.rb
https://jira.ets.berkeley.edu/jira/browse/BOAC-4115
=> BOAC-4115, Teena change per BOA element id change: from 'course-units-blah' to 'units-blah'

pages/boac/boac_degree_check_page.rb, pages/boac/boac_degree_check_template_page.rb, spec/boac/boac_degree_check_spec.rb
Plus more naming convention changes.
=> Tests for unassigned course edits

models/boac/degree_progress/degree_progress_template.rb, models/boac/degree_progress/degree_reqt_category.rb, pages/boac/boac_degree_check_page.rb, pages/boac/boac_degree_template_page.rb, pages/canvas/canvas_announce_discuss_page.rb, pages/page.rb, spec/boac/boac_degree_check_unit_reqts_spec.rb, test_data/test-data-boac.json
The functionality isn't finished, and the reqts aren't fully defined.  Needless to say, these tests don't work yet and will need revision.
=> Tests for dragging and unit reqts

models/boac/degree_progress/degree_progress_checklist.rb, models/boac/degree_progress/degree_unit_reqt.rb, pages/boac/boac_degree_check_page.rb, pages/junction/canvas_create_course_site_page.rb, spec/boac/boac_degree_check_unit_reqts_spec.rb, spec/junction/canvas_lti_course_site_creation_spec.rb, spec/junction/canvas_lti_mailing_lists_spec.rb
Plus a couple Junction test fixes.
=> Fill in BOA unit fulfillment tests

pages/boac/boac_degree_check_batch_page.rb
https://jira.ets.berkeley.edu/jira/browse/BOAC-4292
Follows BOA PR https://github.com/ets-berkeley-edu/boac/pull/3168
=> BOAC-4292, BOA degree check: dashes instead of spaces in /batch page element ids

pages/boac/boac_cohort_pages.rb, pages/boac/boac_student_page.rb, spec/boac/boac_sis_student_data_spec.rb
Mostly reformatting plus a couple new tests
=> BOA SIS data test reformatting and to-doing

models/boac/appts_and_notes/appointment_status.rb, models/boac/degree_progress/degree_completed_course.rb, models/boac/degree_progress/degree_course.rb, pages/boac/boac_class_pages.rb, pages/boac/boac_group_page.rb, scripts/boac_class_pages_script.rb, spec/boac/boac_class_pages_spec.rb, spec/boac/boac_curated_group_spec.rb, spec/boac/boac_degree_check_courses_spec.rb, spec/boac/boac_degree_check_mgmt_spec.rb
=> More BOA tests and tweaks

pages/boac/boac_api_student_page.rb, pages/boac/boac_class_pages.rb, pages/boac/boac_degree_check_page.rb, pages/boac/boac_pages.rb, pages/boac/boac_search_results_page.rb, pages/boac/boac_student_page_advising_note.rb, scripts/boac_sis_student_data_script.rb, spec/boac/boac_appts_drop_in_spec.rb, spec/boac/boac_degree_check_mgmt_spec.rb, spec/boac/boac_degree_template_spec.rb, spec/boac/boac_navigation_spec.rb, spec/boac/boac_note_content_spec.rb, spec/boac/boac_search_appt_spec.rb, spec/boac/boac_user_role_director_spec.rb, util/nessie_timeline_utils.rb
=> Capture more BOA data points to support EDL cutover

pages/boac/boac_api_student_page.rb, pages/canvas/canvas_assignments_page.rb, pages/canvas/canvas_grades_page.rb, pages/squiggy/squiggy_asset_library_list_view_page.rb, pages/squiggy/squiggy_engagement_index_page.rb, scripts/boac_sis_student_data_script.rb, spec/squiggy/asset_library_asset_creation_spec.rb, spec/squiggy/canvas_discussions_spec.rb, util/utils.rb
Plus a handful of Squiggy and Canvas test fixes.
=> More BOA data scraping

util/nessie_filter_utils.rb, util/nessie_utils.rb
First part of Teena's cutover.
=> Switch to new RDS table

models/boac/appts_and_notes/timeline_record_source.rb, models/boac/boac_test_config.rb, spec/boac/boac_filtered_group_spec.rb, spec/boac/boac_note_content_spec.rb, spec/boac/boac_search_note_spec.rb, util/nessie_timeline_utils.rb, util/nessie_utils.rb, util/oec_utils.rb
Plus a little historical student cleanup.
=> Add tests for BOA history notes, with TODOs

pages/squiggy/squiggy_asset_library_detail_page.rb
https://jira-secure.berkeley.edu/browse/COL-1715
Per https://github.com/ets-berkeley-edu/squiggy/pull/263
=> COL-1715, Squiggy: change to asset title element id

pages/squiggy/squiggy_login_page.rb
Corresponding Squiggy PR: https://github.com/ets-berkeley-edu/squiggy/pull/340
=> [Teena] COL-1769: fix 'id' in dev_auth login form

models/squiggy/squiggy_asset.rb, pages/junction/api_academics_roster_page.rb, pages/junction/canvas_course_add_user_page.rb, pages/junction/canvas_e_grades_export_page.rb, pages/squiggy/squiggy_whiteboard_page.rb, spec/junction/canvas_lti_e_grades_export_spec.rb, spec/junction/canvas_lti_rosters_spec.rb
Teena was a little intolerant of weird SIS data.
=> Junction and Squiggy test fixes

pages/squiggy/squiggy_engagement_index_page.rb, pages/squiggy/squiggy_impact_studio_page.rb, spec/squiggy/impact_studio_activity_network_spec.rb, util/squiggy_utils.rb, util/utils.rb
=> Activity network tests revived

models/squiggy/squiggy_test_config.rb, pages/squiggy/squiggy_impact_studio_page.rb, pages/squiggy/squiggy_pages.rb, pages/squiggy/squiggy_whiteboard_page.rb, spec/squiggy/canvas_silos_spec.rb, spec/squiggy/impact_studio_event_drops_spec.rb, spec/squiggy/impact_studio_profile_summary_spec.rb
=> Tests for Activity Timeline

pages/boac/boac_degree_check_create_page.rb, pages/boac/boac_degree_check_page.rb, pages/boac/boac_degree_template_page.rb, pages/boac/boac_filtered_students_page_filters.rb, pages/boac/boac_flight_data_recorder_page.rb, pages/boac/boac_pages.rb, pages/boac/boac_pages_create_note_modal.rb, pages/boac/boac_pax_manifest_page.rb, pages/canvas/canvas_page.rb, pages/canvas/canvas_people_page.rb, pages/junction/canvas_course_add_user_page.rb, pages/junction/canvas_e_grades_export_page.rb, pages/junction/canvas_rosters_page.rb, pages/junction/my_toolbox_page.rb, pages/page.rb, pages/squiggy/squiggy_impact_studio_page.rb, spec/squiggy/impact_studio_assets_spec.rb, spec/squiggy/impact_studio_profile_summary_spec.rb
A lot of this is fixing a misleading method name.
=> Fix Impact Studio tests

pages/boac/boac_flight_data_recorder_page.rb, pages/squiggy/squiggy_asset_library_metadata_form.rb, pages/squiggy/squiggy_engagement_index_page.rb, pages/squiggy/squiggy_whiteboard_page.rb, spec/squiggy/canvas_silos_spec.rb, spec/squiggy/whiteboard_assets_spec.rb
Fixes bugs in tests and extends waits for UI updates
=> Final Squiggy 4.2 test updates

pages/boac/boac_group_students_page.rb, spec/boac/boac_filtered_group_spec.rb
No need to make 14 filtered groups.  One is plenty.
=> Stop over-testing filtered groups

pages/boac/boac_api_notes_page.rb, pages/boac/boac_api_student_page.rb, pages/boac/boac_class_list_view_page.rb, pages/boac/boac_pages.rb, pages/boac/boac_student_page.rb, pages/squiggy/squiggy_engagement_index_page.rb, spec/boac/boac_class_pages_spec.rb, spec/boac/boac_note_mgmt_spec.rb, spec/boac/boac_user_mgmt_spec.rb, spec/boac/boac_user_role_restricted_spec.rb, util/utils.rb
Fixes misc odd test problems, mostly with Selenium upgrade.
=> Test fixes for BOA v5.15

pages/boac/boac_admit_pages.rb, pages/boac/boac_api_notes_page.rb, pages/boac/boac_cohort_student_pages.rb, pages/boac/boac_filtered_students_page.rb, pages/boac/boac_filtered_students_page_filters.rb, pages/boac/boac_group_pages.rb, pages/boac/boac_pages.rb, pages/boac/boac_search_form.rb, pages/boac/boac_search_results_page.rb, pages/element.rb, spec/boac/boac_authorized_user_spec.rb, spec/boac/boac_curated_admit_group_spec.rb, spec/boac/boac_curated_group_spec.rb, spec/boac/boac_filtered_cohort_spec.rb, spec/boac/boac_note_batch_spec.rb, spec/boac/boac_note_mgmt_spec.rb, spec/boac/boac_search_admit_spec.rb, spec/boac/boac_search_appt_spec.rb, spec/boac/boac_search_class_spec.rb, spec/boac/boac_search_note_spec.rb, spec/boac/boac_search_student_spec.rb, spec/boac/boac_topic_mgmt_spec.rb, spec/boac/boac_user_role_advisor_spec.rb, spec/boac/boac_user_role_restricted_spec.rb, util/nessie_filter_utils.rb, util/spec_helper.rb
- new search UI
- cohort filter updates
- misc test fixes
=> Tests for BOA v5.16

load_tests/squiggy_locust.py, models/course.rb, pages/page.rb, scripts/csv_compare_script.rb
Plus a couple unrelated changes
=> First pass on a Day of the Locust for Squiggy

pages/boac/boac_pax_manifest_page.rb, pages/ripley/ripley_mailing_lists_page.rb, pages/ripley/ripley_roster_photos_page.rb, spec/boac/boac_authorized_user_spec.rb, spec/boac/boac_filtered_cohort_spec.rb, spec/boac/boac_flight_data_recorder_spec.rb, spec/boac/boac_navigation_spec.rb, spec/boac/boac_note_batch_spec.rb, spec/boac/boac_note_content_spec.rb, spec/boac/boac_search_admit_spec.rb, spec/boac/boac_search_note_spec.rb, spec/boac/boac_user_mgmt_spec.rb, spec/boac/boac_user_role_advisor_spec.rb, test_data/test-data-boac.json, util/boac_utils.rb
Plus some additional UI elements for Ripley tests.
=> BOA v5.16 test fixes

pages/canvas/canvas_people_page.rb, spec/ripley/official_sections_spec.rb, util/ripley_utils.rb
Tests won't quite work till Ripley can create her own sites too.
=> First steps to verifying Ripley site membership

pages/ripley/ripley_create_course_site_page.rb
https://jira-secure.berkeley.edu/browse/RIP-420
https://github.com/ets-berkeley-edu/ripley/pull/505
=> RIP-420, /course_site_create: text_field element ID changes

pages/ripley/ripley_official_sections_page.rb
https://jira-secure.berkeley.edu/browse/RIP-476
Pairs nicely with https://github.com/ets-berkeley-edu/ripley/pull/542
=> [Teena] RIP-476, update navigate_to path of standalone official_sections tool

models/ripley/ripley_test_config.rb, spec/ripley/customizations_and_add_user_spec.rb, spec/ripley/e_grades_export_spec.rb, spec/ripley/roster_photos_spec.rb, spec/ripley/welcome_email_spec.rb, util/ripley_utils.rb
Mostly rearranging the furniture.
=> Reorganize Ripley test config and initialization

pages/ripley/ripley_add_user_page.rb
https://jira-secure.berkeley.edu/browse/RIP-603
It seems that this is the only necessary change. @pfarestveit should review.
=> RIP-603, Find Person to Add: expect radio buttons, not select

load_tests/ripley_locust.py, requirements.txt
The dependencies are (very) updated now, so the other load tests will be busted until they're also updated.
=> Flowers for Algernon, Locusts for Ripley

pages/boac/boac_degree_check_page.rb
https://jira-secure.berkeley.edu/browse/BOAC-5356
=> [Teena] BOAC-5356, /degree_progress accent color selector ID change
